### ISSUE TITLE
Angular Universal SSR issue due to `window` being present

### ISSUE THREAD

**Issue by PBartrina** [tjoskar/ng-lazyload-image#101]
Since there is no window context on the server, all the `window` references makes the server side rendering fail. 

I'd suggest to use some browser checking (universal has one) before using `window`.

**Comment by tjoskar** [comment]
It should be nice to be independent of the browser and the window reference but I do not have the time to investigate the matter right now.
I do, however, gladly accept pull requests.

**Comment by PBartrina** [comment]
Bookmarking this issue to investigate, then

**Comment by tjoskar** [comment]
Nice, let me know if I can help you in any way

**Comment by MurhafSousli** [comment]
@PBartrina I will do it

**Comment by kevinphelps** [comment]
I opened pull request #149 to fix this issue.

**Comment by tjoskar** [comment]
Fixed in version 3.1.1, thanks @kevinphelps
