### ISSUE TITLE
Displaying local images for errorImages?

### ISSUE THREAD

**Issue by donjae** [tjoskar/ng-lazyload-image#138]
Hi,

Whenever I try to reference my local images (png/svg), it's not really displaying for the error. I've tried http connections, and they work fine, but just not local references (`"url('..filepath')"`). 

Is it possible with this package, and if so, you mind showing an example of the syntax?

**Comment by tjoskar** [comment]
Hi,

I'm not sure I follow. All images will always be loaded over the http(s)-protocol (except if you serve your app over some ofter protocol, like `file` or `ftp`).

You should be able to lazy load your local `png/svg` with just:
```html
<img [lazyLoad]="'../path/to/my-image.png'">
```  

which will be transform to:
```html
<img src="../path/to/my-image.png">
```

If you for some reason want to use the `css` attribute: `url`, you should use a `div`-tag instead:

```html
<div [lazyLoad]="'../path/to/my-image.png'"></div>
```

which will be transform to:
```html
<div style="background-image: url('../path/to/my-image.png');"></div>
```

**Comment by donjae** [comment]
Ah, thanks. I've been miswriting the path as `[lazyLoad]="pathDirection"`, hence my erorr:

Like so: `pathDirection = "url('../path/to/my-image.png')"`

Thanks!
