### ISSUE TITLE
Dynamic image variable without *ngIf or template

### ISSUE THREAD

**Issue by raphael22** [tjoskar/ng-lazyload-image#140]
Hi,

I was wondering how could I change a "image" variable without reloading the img node.

I made a Plunker with basic exemple : [plnkr](https://plnkr.co/edit/POW6sHEs6Nfrs31K4VKV?p=preview) 

First a lowres cat is load then the high-res version, 1sec later I change the variables for a nature image which never load.

This does work if embed with a ng-if but this break my background transition since isn't the same img node element.

Thanks.

**Comment by btdevn** [comment]
I have a similar issue, I need to update an image every few seconds based on server response. but presently, once loaded there doesn't seem to be any method to trigger an update on the element.

**Comment by tjoskar** [comment]
Hi,

This package do not currently support to change the image on the fly. I think however it should be fairly easy to implement. Something like this:

```ts
propertyChanges;

constructor(el: ElementRef, ngZone: NgZone) {
  this.elementRef = el;
  this.ngZone = ngZone;
  this.propertyChanges$ = new BehaviorSubject({});
}

ngOnChanges() {
  this.propertyChanges$.next({
    lazyImage: this.lazyImage,
    defaultImage: this.defaultImage,
    errorImage: this.errorImage,
    scrollTarget: this.scrollTarget,
    scrollObservable: this.scrollObservable,
    offset: this.offset
  });
}

ngAfterContentInit() {
  this.ngZone.runOutsideAngular(() => {
    this.scrollSubscription = this.propertyChanges$
      .switchMap(properties => {
        let events$;
        if (properties.scrollObservable) {
          events$ = properties.scrollObservable.startWith('')
        } else {
          events$ = getScrollListener(properties.scrollTarget);
        }
        return events$.let(lazyLoadImage(this.elementRef.nativeElement, properties.lazyImage, properties.defaultImage, properties.errorImage, properties.offset));
      })
      .subscribe(() => {});
  });
}
```
 
I will gladly accept pull requests :)

**Comment by tjoskar** [comment]
Hi @raphael22, @btdevn.
Can you try `3.3.1` to see if it solves your issue?

**Comment by youssmak** [comment]
@tjoskar thank you for the on the fly image update feature 👏 
it works 👌
