### ISSUE TITLE
When using scrollTarget, the image starts to load only if scrolling the view port.

### ISSUE THREAD

**Issue by vincent-cm** [tjoskar/ng-lazyload-image#141]
The image does not start to load, instead of the default image, unless I scroll the page.

**Comment by tjoskar** [comment]
Hi,

What did you assign to `scrollTarget`? Do you get any warnings in the browser console?

**Comment by tjoskar** [comment]
have you seen the scroll container examples on: http://tjoskar.github.io/ng-lazyload-image (and the usage: https://github.com/tjoskar/ng-lazyload-image/blob/d4b3d71f918b83aa18c5d4f7819e92cd2630bd1a/example/scroll-container.component.ts#L35)

**Comment by vincent-cm** [comment]
I think the scrollTarget get assigned correct since if not the lazy load not work.
Is it because the scrolling element under scrollTarget has nested structure like this:

<div #scrollTarget>
<div>
<div>
	<img lazyload>
</div>
</div>
</div>

**Comment by tjoskar** [comment]
Nested structure is fine. But just to be clear, you do pass the scroll target to the directive?

```html
<div #scrollTarget>
  <div>
    <div>
      <img [lazyLoad]="image" [defaultImage]="defaultImage" [scrollTarget]="scrollTarget">
    </div>
  </div>
</div>
```

**Comment by tjoskar** [comment]
@vincent-cm, did you solve the problem? I will close this issue now but feel free to reopen it.
