### ISSUE TITLE
Unexpected module 'LazyLoadImageModule' declared by the module

### ISSUE THREAD

**Issue by izupet** [tjoskar/ng-lazyload-image#143]
I am using angular cli and trying to install this package but getting this error Unexpected module 'LazyLoadImageModule' declared by the module 'AppModule'. My version is 3.1.0.

**Comment by izupet** [comment]
Added LazyLoadImageModule under declarations instead imports.

**Comment by tjoskar** [comment]
Okey, that seems weird. I will take a look at it. Thanks!
