### ISSUE TITLE
Cant update the image

### ISSUE THREAD

**Issue by LeVadim** [tjoskar/ng-lazyload-image#144]
Hey there!
I have 10 images preloaded, but when i am applying my filters, images are being changed but some of them remains.(depends on my filter options)
Images become broken and they are not working.
Looking to solve this issue here,
Thanks!

**Comment by tjoskar** [comment]
Hi, 
Can you give me some example code? Are your filter asynchronous? Or synchronous?

**Comment by tjoskar** [comment]
@LeVadim, did you solve the issue? I will close this issue now but feel free to reopen it.
