### ISSUE TITLE
Image tag/html is rendering before sources url are complete?

### ISSUE THREAD

**Issue by donjae** [tjoskar/ng-lazyload-image#145]
Hi,

I'm noticing this weird issue where I notice the urls are being cutoff.  An example how it looks below:

when it's rendered in the dom, the html looks like this: 
```
<img _ngcontent-c18="" class="image-preview mat-card-sm-image" 
id="img-prev" md-card-sm-image="" 
ng-reflect-lazy-image="https://storage.cloud.google.c" 
ng-reflect-default-image="https://storage.cloud.google.c" 
src="....(this works)">
```

in the source code though, the url's look like this 

```
<img md-card-avatar
            [errorImage]="'../../assets/svg/ic_mood_grey_48px.svg'" 
            [defaultImage]="'https://storage.cloud.google.com/{company}/profile-thumbnail/' + image.id" 
            [lazyLoad]="'https://storage.cloud.google.com/{company}/profile/' + image.id">
```

Anyone experiencing this issue?

**Comment by tjoskar** [comment]
This sound super weird. Do you get the same behavior if you remove `md-card-avatar`?

Have you tried to debug `ng-lazyload-image` in the devtools to see if the lib gets the full url-string?

**Comment by donjae** [comment]
Yeah, tried it without md-card-avatar thinking it might be the issue before, but didn't make a difference. 

As for the devtools, not really sure how to debug it? I did apply a `ngAfterViewInit` and tied a `  @ViewChild('image') image: ElementRef;` to the lazyloaded image tag to see what was printed out, and it was the same thing on the dom. (Sorry in advance for being a scrub)

**Comment by tjoskar** [comment]
@donjae, do you still have this issue?

Just to be clear. Does this code:
```html
<img 
  md-card-avatar
  [errorImage]="'../../assets/svg/ic_mood_grey_48px.svg'" 
  [defaultImage]="'https://storage.cloud.google.com/{company}/profile-thumbnail/' + image.id" 
  [lazyLoad]="'https://storage.cloud.google.com/{company}/profile/' + image.id">
```

transforms to something like this:
```html
<img
  _ngcontent-c18=""
  class="image-preview mat-card-sm-image" // Where is the 'ng-lazyloaded'-class?
  id="img-prev"
  md-card-sm-image="" 
  ng-reflect-lazy-image="https://storage.cloud.google.c" // This is just weird
  ng-reflect-default-image="https://storage.cloud.google.c" 
  src="....(this works)">
```

Is the link in `src` also truncated?

**Comment by donjae** [comment]
So, yeah what you said sums up the issue where url's are being truncated. I actually had to switch to the regular img html tag which avoids this problem.

Still using the package tho, but just on less crucial features. 

Had a theory that maybe it's a websocket + lazy image issue where the data comes at an odd rate, messed around with it in terms of initializing the string between ngOnInit/ngOnChanges and pushing the  data through observables but still no resolve.

**Comment by tjoskar** [comment]
I have honestly no idea.
Can you add a `console.log` in the directive? ie. add `console.log('lazyImage: ', _this.lazyImage, 'defaultImage: ', _this.defaultImage, 'errorImage: ', _this.errorImage)` in the function `LazyLoadImageDirective.prototype.ngAfterContentInit` at line ≈25 in file `node_modules/ng-lazyload-image/src/lazyload-image.directive.js`.
So it looks something like:
```js
LazyLoadImageDirective.prototype.ngAfterContentInit = function () {
  var _this = this;
  console.log('lazyImage: ', _this.lazyImage, 'defaultImage: ', _this.defaultImage, 'errorImage: ', _this.errorImage);
  this.ngZone.runOutsideAngular(function () {
```
Just to see when the directive gets for inputs.

**Comment by mohammadrafigh** [comment]
I have the same issue here. I don't see any src attribute in img element and the ng-reflect-lazy-image is truncated.

**Comment by donjae** [comment]
@tjoskar Hey sorry for the stale reply, but haven't worked with this package in awhile. @mohammadrafigh could probably provide more input (sorry)

**Comment by tjoskar** [comment]
@mohammadrafigh, can you give me some (html) code how you are using `ng-lazyload-image`?

**Comment by mohammadrafigh** [comment]
@donjae @tjoskar sure, I will make a plunker asap.

**Comment by mrcleanandfresh** [comment]
I'm having the same problem. This is what I get when I added the logging as you mentioned:
`lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_chip_cots.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_chip_cots_multi-anode.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_axial-hermetic_standard.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_chip_commercial.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_axial-hermetic_space.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_axial-hermetic_commercial.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_axial_standard.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/supercapacitor.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40 
lazyImage:  http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/supercapacitor_snap-in.jpg defaultImage:  http://www.fillmurray.com/600/600 errorImage:  undefined
lazyload-image.directive.js:40`

**Comment by mrcleanandfresh** [comment]
I thought it might have been because I was using a bootstrap modal, and the scroll event wasn't reaching the window, so I put:
```JavaScript
const target = document.querySelector('body #scrollTargetModal');
if (target) {
  this._scrollTarget = target;
}
```
Inside `ngOnInit` because `ngAfterViewInit` was too late. Here's the changed HTML:
```HTML
<img src="http://www.fillmurray.com/600/600" [scrollTarget]="_scrollTarget"  [lazyLoad]="attachment.guid" [offset]="150" *ngIf="!attachment.isUnPreviewableFile" class="img-fluid" />
```
Same issue though. No dice.

**Comment by tjoskar** [comment]
It looks like `ng-reflect-*` are only used for debug purpose and that they only take the first 30 chars of the value, so that is working as expected. 
However, the images are not loaded for you for some reason. 

@mrcleanandfresh, can you try to hard code the image path and remove the offset:
```html
<div style="font-size: 9em; text-align: center">
  <span *ngIf="attachment.isUnPreviewableFile" class="fa fa-file-o" style="padding: 3px 0;"></span>
  <img [defaultImage]="'http://www.fillmurray.com/600/600'" [lazyLoad]="'http://kevins-macbook-pro.local/wordpress/wp-content/uploads/2017/08/tantalum_chip_cots.jpg'" class="img-fluid" />
</div>

**Comment by mrcleanandfresh** [comment]
@tjoskar I tried that as a debugging step. When angular initially loads all the image containers they have no images in them, but since they’re in the active window your directive renders them.

So I ended up putting a min-height and min-width of 150 pixels on the containers. That effectively loaded less images, but that was expected.

Then when I would scroll past the active area, none of the images would load, but I could see the hardcoded values found in the reflect properties. It wasn’t until I changed the scroll target to an element (see comment above yours) when I specifically defined the overflow-y property in CSS that it actually started working the way I expected. 

 That is, with one exception — and this is unrelated, but when we tried to use the (onLoad) event to determine when an image was requested, it only fired for this initial images that were within the active area.

**Comment by tjoskar** [comment]
> [...] So I ended up putting a min-height and min-width of 150 pixels on the containers. That effectively loaded less images, but that was expected.

Yes, that is expected and nothing I can do about it :) And I would say it is best practice to always set a hight and width to an image to avoid the content to jump around when the browser renders the images.

> It wasn’t until I changed the scroll target to the specifically defined scrollable element (see comment above yours) where it actually started working the way I expected.

I misunderstood your comment above, sorry about that. You need to set scroll target if you aren't scrolling the window. You should however be able to change the scroll target on the fly but I do not recommend it since `ng-lazyload-image` will "reboot" every time it gets new inputs. 

> However, there is one exception — and this is unrelated, but when we tried to use the onLoad event 

Humm.. so you get an event for the first image? But not the images that are loaded when you are scrolling? It would be nice if you could create an issue for it, thanks.

**Comment by tjoskar** [comment]
I will close this issue but please feel free to reopen this issue if the problem still occurs.
