### ISSUE TITLE
Import error!

### ISSUE THREAD

**Issue by michaelspeed** [tjoskar/ng-lazyload-image#147]
i am getting this error

> LazyLoadImageDirective is part of the declarations of 2 modules: LazyLoadImageModule and AppModule! Please consider moving LazyLoadImageDirective to a higher module that imports LazyLoadImageModule and AppModule. You can also create a new NgModule that exports and includes LazyLoadImageDirective then import that NgModule in LazyLoadImageModule and AppModule.

 

app.module.ts - 
`import {LazyLoadImageDirective, LazyLoadImageModule} from "ng-lazyload-image";
@NgModule({
  declarations: [
    ...
      LazyLoadImageDirective
  ],
  imports: [
    ...
      LazyLoadImageModule
  ],
  providers: [...],
  bootstrap: [..]
})`

AngularVersion : '4.1.0'

**Comment by tjoskar** [comment]
Hi,

Try to remove `LazyLoadImageDirective` from `declarations` and just include `LazyLoadImageModule` in `imports`.

**Comment by michaelspeed** [comment]
Using Only LazyLoadImageModule - 
i get this - 
`
Unhandled Promise rejection: Template parse errors:
Can't bind to 'lazyload' since it isn't a known property of 'img'.
`

**Comment by tjoskar** [comment]
Are you sure you have written `lazyLoad`? And not `lazyload` in your component?
Eg. `<img [lazyLoad]="image">` and **not** `<img [lazyload]="image">`

**Comment by michaelspeed** [comment]
OOps Sorry! got it thanx
