### ISSUE TITLE
Uncaught ReferenceError: __extends is not defined

### ISSUE THREAD

**Issue by rrundle** [tjoskar/ng-lazyload-image#151]
This is a runtime error that shows up referencing my app.config.ts file. Hmmm. 

Any clue what this might be? 

Using Ionic 2: 
Here's my html, Component file is as requested:
`<img [defaultImage]="spinner" offset="100" [lazyLoad]="picture [scrollObservable]="container.ionScroll">`

**Comment by tjoskar** [comment]
Just to be clear, if you remove `<img [defaultImage]="spinner" offset="100" [lazyLoad]="picture [scrollObservable]="container.ionScroll">` from your template, does the error disappear?

**Comment by tjoskar** [comment]
It so, what version of angular are you using?

**Comment by rrundle** [comment]
If i remove the html element the error does not disappear. I narrowed it down to the error appearing when I declare the module in my app.module imports. I do have `noEmitHelpers: true` and the version of Angular I'm using is 2.4.8, rxjs version is 5.2.0.

**Comment by tjoskar** [comment]
I guess you are targeting ES2015? Or using Babel as a build step. 
If you have set `noEmitHelpers: true` and targeting es5, you are responsible to include the helper functions. See this blog for more information: https://blog.mariusschulz.com/2016/12/16/typescript-2-1-external-helpers-library 
However, if you are targeting es6 or above this lib (lazyload) should just work and I will treat this as a bug. 
So can you give me your tsconfig file?

**Comment by rrundle** [comment]
you're right, my target is ES2015. Thank you for sharing the blog!!
