### ISSUE TITLE
IE doesnt show the images in the first load of the page

### ISSUE THREAD

**Issue by aelghanam** [tjoskar/ng-lazyload-image#156]
Hello,

Do you have any idea what could cause that the images dont get displayed after the first reload of the page on IE, though they can be found in the HTML, but if you do a hard refresh it works.

Thanks in advance 👍

**Comment by tjoskar** [comment]
Hi,
I have no idea. What version of IE are you using?

**Comment by tjoskar** [comment]
I can't reproduce this. Let me know if you still have the issue.
