### ISSUE TITLE
Performance issue while loading and scrolling

### ISSUE THREAD

**Issue by raxim1** [tjoskar/ng-lazyload-image#157]
I'm using ionic, but ionic hasn't got working ionic lazy loading, i tried out this solution.

What i noticed:

1, When the page are loaded it's not lazy loading until i send a manually created scroll event. (container.ionScroll) - i haven't noticed any additional bug, works as expected.
2, This library is too heavy, i have measured 4-5 times slowness against just use <img> purely.

Although my initial problem has been solved, i considered to raise a a bug report against it.

Solution:
I'm not using this library, replaced canvas implementation of mine with svg approach.

**Comment by tjoskar** [comment]
Hi,

> 1, When the page are loaded it's not lazy loading until i send a manually created scroll event. (container.ionScroll) - i haven't noticed any additional bug, works as expected.

I know it has been some problems with this library and ionic. If you manually have to send a scroll event I guess that the image has been rendered outside of the viewport for some reason (ionic do that in some cases).

> 2, This library is too heavy, i have measured 4-5 times slowness against just use  purely.

What do you mean by heavy? Are you talking about the file size, time to first meaningful paint or response time when using your application?

> ... 4-5 times slowness ...
This is absolutely enormous

**Comment by tjoskar** [comment]
I will close this for now but please provide more information if you can.
