### ISSUE TITLE
Horizontal scroll ionic2

### ISSUE THREAD

**Issue by kodeine** [tjoskar/ng-lazyload-image#158]
Following does not load the image on horizontal scroll.
```
            <ion-scroll scrollX="true" #lazyContainer>
                <!--<img class="thumbnail-avatar" *ngFor="let item of items" src="http://placehold.it/350x150">-->
                <img class="thumbnail-avatar-square spacer" *ngFor="let item of recent"
                     (click)="tapped(item)"
                     [scrollObservable]="lazyContainer.ionScroll"
                     [lazyLoad]="item.avatar">
            </ion-scroll>
```

![image](https://cloud.githubusercontent.com/assets/8620059/26601352/32569f0a-4545-11e7-94b8-757c53bf0c61.png)

**Comment by tjoskar** [comment]
Hi, 

I guess that `lazyContainer.ionScroll` only emits events when scrolling vertically for some reason. Can you try to print the value of `ionScroll` to see if its emits any values when you are scrolling.

```html
<ion-scroll scrollX="true" #lazyContainer>
  <img class="thumbnail-avatar-square spacer" *ngFor="let item of recent"
    (click)="tapped(item)"
    [scrollObservable]="lazyContainer.ionScroll"
    [lazyLoad]="item.avatar">
  {{ lazyContainer.ionScroll | async | json }}
</ion-scroll>
```

**Comment by tjoskar** [comment]
@kodeine please feel free to reopen this issue if the problem still occurs

**Comment by fmendoza** [comment]
Hi there,

First... @tjoskar congratulations. This work as expected on Ionic 3.9.2. However, I have the same issue with <ion-scroll>. I just tried to print the value of the ionScroll and is returning null. So I guess that's the reason is not working. 

Any workaround for this ionic issue?

**Comment by fmendoza** [comment]
Update: I tried the same with a working example and also ionScroll is returning null?

**Comment by fmendoza** [comment]
Got it working. The key is to set scrollTarget to `scroll._scrollContent.nativeElement`

![](http://g.recordit.co/LUTPACP0cQ.gif "")

Full code below

```javascript
<ion-scroll scrollX="true" direction="x" #scroll1>
    <div class="item" margin *ngFor="let item of newItems"
      (click)="goToItemPage(item)">
      <img src="./assets/imgs/placeholder.png"
        [lazyLoad]="item.photoThumb?.url()"
        [scrollTarget]="scroll1._scrollContent.nativeElement" />
        <div text-center text-wrap>
          <p no-margin>{{ (item.shortName || item.name) | excerpt:17 }}</p>
        </div>
    </div>
  </ion-scroll>
`

**Comment by shariajoe** [comment]
Hi @fmendoza I have multiple rows where each should be horizontally scrollable and lazy load images
However only visible rows display images on first load.
Scrolling vertically to expose other rows does not trigger image load.
I would like to enable load of these images on vertical scroll of my ion-content and horizontal scroll of my ion-scroll
Kindly assist
