### ISSUE TITLE
Negative offset to lazyload image that is just out of viewport

### ISSUE THREAD

**Issue by Luukschoen** [tjoskar/ng-lazyload-image#160]
Hi, 

Here I am again ;). I was wondering if it was somehow already possible to create a negative offset? I know it counteracts with lazyloading images in the viewport, but the main idea is that you could set a negative offset so the image which is just out of the viewport, is already loaded.

I've got lists with products and it would be nice to already load the image that is going to be in te viewport, just before the user is going to scroll there. Is something like this already possible or could you give some pointers?

**Comment by tjoskar** [comment]
Hi,

Yeah, you should be able to set a offset to the image, like: 

```html
<img [defaultImage]="defaultImage" [lazyLoad]="image" offset="100">
```

Where `offset` is the number of pixels (100 in this case) the image should be loaded before it's in the viewport.

**Comment by Luukschoen** [comment]
Off course. I totally thought that offset totally did the opposite (which doesn't make sense haha). Thank you very much.
