### ISSUE TITLE
Bug: All Images not loaded until I scroll

### ISSUE THREAD

**Issue by AhsanAyaz** [tjoskar/ng-lazyload-image#168]
For some reason, even if I use 
```
<img *ngIf="image" [lazyLoad]="image" [defaultImage]="defaultImage">
<img *ngIf="!image" [src]="defaultImage">
```

Only the first image loads until I scroll down  a bit. 
Using Angular4 with AngularCLI. With angular material2 and angular2-masonry. 
Screenshot attached (the medium icon image is the default image):

<img width="793" alt="screen shot 2017-07-02 at 1 06 40 am" src="https://user-images.githubusercontent.com/9844254/27765106-bcc77c54-5ec2-11e7-9618-9ee3140a2001.png">

Possible duplicate of #157

**Comment by tjoskar** [comment]
Hi @AhsanAyaz, is this site live (with or without) `ng-lazyload` so I can take a look at it?

> Only the first image loads [...]
Is it always the first image that gets loaded? Or can it be the second one or maybe none at all?

> [...] until I scroll down a bit
Becomes all images visible when you scroll?

**Comment by tjoskar** [comment]
Are you using `md-card`? I tried to reproduce the issue in a pluker but did not succeed: https://plnkr.co/edit/Rnt4LBpZ0zpNQvAEUe4v?p=preview

**Comment by tjoskar** [comment]
@AhsanAyaz, did you solve your issue?

**Comment by SmirnovM91** [comment]
I have the same situation. Do you have some advice?

**Comment by tjoskar** [comment]
Hi @SmirnovM91, 

I need to get more information if I should be able to help you :)

Please open a new issue if it does not work for you.
