### ISSUE TITLE
Lazy loading images inside modals/popovers [ng-bootstrap]

### ISSUE THREAD

**Issue by meiordac** [tjoskar/ng-lazyload-image#169]
I am using the latest version of Angular with https://github.com/ng-bootstrap/ng-bootstrap and when I open a modal (or popover) only the default image is displayed even if I set the scrollTarget like this:

```
<div class="modal-body"  #scrollableDiv>
  <p> Text: </p>
    <img [defaultImage]="defaultImage"
      [lazyLoad]="image"
      [scrollTarget]="scrollableDiv"
      [offset]="offset">
</div>
```

My solution right now is to not use the library in modals/popovers but it is one of our requirements

Thanks in advance

**Comment by tjoskar** [comment]
Hi @meiordac, 

I created a plunker but was not able to reproduce the error: http://plnkr.co/edit/opO6BFM1VfvAhi34Du9j?p=preview

Can you reproduce the issue in a plunker?

**Comment by tjoskar** [comment]
@meiordac, did you solve the issue?
