### ISSUE TITLE
Image not showing withFirebaseListObservable

### ISSUE THREAD

**Issue by brijmcq** [tjoskar/ng-lazyload-image#174]
Hi everyone!
I am trying to use ng-lazyload-image with angularfire. My problem is that only the first image is loaded and the rest of the items don't work. I saw somewhere here to put *ngIf to check first if its null but still not working.
Here's my code
```
<div *ngFor="let tour of tours$ | async">
  <md-card>
      <img  *ngIf="tour?.imageUrl" 
           md-card-lg-image  [lazyLoad]="tour?.imageUrl"
           [defaultImage]="defaultImage"
           [offset]="100"
      >
   //... more code
```

Hope somebody can help me with this. Thank you!

**Comment by tjoskar** [comment]
Hi,

I created a [plnkr](http://plnkr.co/edit/N57efvc8QWFRtHxC0rpS?p=preview) but was not able to reproduce the issue.

I faked the `tours$` observable but it should have the same effect as with angularfire. 

Can you take a look at my plnkr and see if you can see any distinguishing differences against your code.

**Comment by brijmcq** [comment]
The plunkr is almost the same code I have. Well the library works for the initial items that you see on the screen, but some items ( below the screen) don't show up. I am not really sure if it is something to do with angularfire. Thank you for your time you are awesome!

**Comment by brijmcq** [comment]
I tracked down the error and it has something to do with md-sidenav. When the sidenav is open, the images don't appear. If you close it, it appears. Just sharing this.
