### ISSUE TITLE
ng-lazyload-image not load on scroll on ionic 2

### ISSUE THREAD

**Issue by ajaysaini95700** [tjoskar/ng-lazyload-image#181]
I have an ionic 2 project . My problem is that when I scroll the screen the images are not showed, but I can see in the network that they are downloaded, so probably my scroll event is not firing

**Comment by tjoskar** [comment]
Hi,

Can you share the html code you are using? Any chance you can create a small github project where you reproduce the issue?

And just to be clear; the image you want to lazy load does not appear on the screen but you can see it being downloaded and you are not using the same image anywhere else on the page?

**Comment by ajaysaini95700** [comment]
here is my html code
<ion-scroll scrollX="true" #container class="applist">
            <div *ngFor="let appdata of appDatas">
                <ion-card>
                    <ion-card-content (click)="appDetails(appdata.nid)">
                        <img [defaultImage]="'https://www.placecage.com/1000/1000'" [lazyLoad]="appdata['App logo']" [scrollObservable]="container.ionScroll">
                    </ion-card-content>
                    <ion-row>
                        <ion-col class="text-align">
                            <p style="-webkit-box-orient: vertical;" [innerHTML]="appdata.title"> </p>
                        </ion-col>
                    </ion-row>
                    <ion-row>
                        <ion-col>
                            <button ion-button icon-left clear small>
                                {{appdata.Rating |rating:appdata.Rating }}<i class="fa fa-star left-margin" aria-hidden="true"></i>
                             </button>
                        </ion-col>
                        <ion-col>

                        </ion-col>
                        <ion-col>
                            <button ion-button icon-left clear small (click)="download(appdata)">
                                <i class="icon icon-download"></i>
                             </button>
                        </ion-col>
                    </ion-row>
                </ion-card>
            </div>
        </ion-scroll> 
Default image is replaced in scroll view which cover screen area refer beforehorizontalscroll.png
and if i scroll then default is not replaced still show default image refer afterhorizontalscrool.png
![beforehorizontalscroll](https://user-images.githubusercontent.com/18483093/28557681-86cb26de-712b-11e7-852b-55495353e1ae.png)
![afterhorizontalscroll](https://user-images.githubusercontent.com/18483093/28557683-8876946e-712b-11e7-8980-66ceec09d4a9.png)

**Comment by tjoskar** [comment]
In your component, do you inheritance from `Content`? If so, can you try to add:

```js
ngOnInit() {
  this.enableScrollListener();
}
```

in your component? (ref. https://github.com/ionic-team/ionic/issues/10938#issuecomment-289851733)

**Comment by tjoskar** [comment]
@ajaysaini95700, Did you solve the problem? I will close this issue now but feel free to reopen it.
