### ISSUE TITLE
The images don't load when navigating between pages

### ISSUE THREAD

**Issue by CarlosAyala** [tjoskar/ng-lazyload-image#182]
Hi!
Great package!.
I have a problem when I navigate between pages of my site.

When the page loads for the first time, the images on screen load fine, but if I go to another page and then come back, the default Image is shown, and the lazy load image don't loads. If I scroll the page, the lazyLoad image is loaded.

**Comment by tjoskar** [comment]
Hi,

Thanks for posting the issue.
Which version of angular are you using (`npm ls @angular/core`)? Are you using the latest version of ng-lazyload-image (`npm ls ng-lazyload-image`)? Are you using `@angular/router` or some other router library? Are you using any animation between the routs/pages? Are you targeting the web or do you use Ionic?
Can you give me an example of the HTML code you are using?

**Comment by nemad** [comment]
Hi,

I have the same issue.

> Which version of angular are you using (npm ls @angular/core)? 


4.3.2
> Are you using the latest version of ng-lazyload-image (npm ls ng-lazyload-image)? 


Yes
> Are you using @angular/router or some other router library? 


angular/router
> Are you using any animation between the routs/pages? 


No
> Are you targeting the web or do you use Ionic?


Web

**Comment by tjoskar** [comment]
Thanks for the info @nemad.
I'm using angular/router on the [demo page](https://tjoskar.github.io/ng-lazyload-image) and it seems to work fine there. Can any of you provide a github repo or a punker ( @CarlosAyala, @nemad ) where the issue can be reproduced?

**Comment by tjoskar** [comment]
Did you solve the problem? I will close this issue now but feel free to reopen it.
