### ISSUE TITLE
Angular Build Optimizer

### ISSUE THREAD

**Issue by coryrylan** [tjoskar/ng-lazyload-image#185]
There is a new webpack plugin in the Angular CLI that can further optimize a production build. They are trying it out behind a flag on the latest RC. Currently the lazy load image directive breaks under these optimizations. To help collaborate on this I have a corresponding issue in the CLI with a repo of how to reproduce it. I'm hoping to try to take some time and try to debug it down in the package. Thanks!

https://github.com/angular/angular-cli/issues/7148

**Comment by coryrylan** [comment]
Closing as this looks to be isolated to Angular CLI build-optimizer and a fix is in the works

**Comment by tjoskar** [comment]
Thanks for bringing up the issue, I will keep an eye on it.
