### ISSUE TITLE
mdSidenav

### ISSUE THREAD

**Issue by sleepdeprivation** [tjoskar/ng-lazyload-image#186]
Hey,

I'm trying to use this in Angular2 from inside the content area of an `mdSidenav` from material UI. My images are given in a list to the component, which then does an `ngFor` on the list to produce image tags.

I tried replacing my image tags with your directive, and the images loaded, but no differently than the default `img` tag... I see them all flash really quickly, and the ones on the bottom seem to get loaded before the ones on top...

Any clue what could be causing this? I think my `sidenav-container` is the element that is scrolling...

I appreciate your work on this plugin btw.

**Comment by sleepdeprivation** [comment]
Update:

when I put a bunch of

`<div>asdf</div>`

above my container, the images cease to load altogether, even after scrolling. It seems I need to figure out how to tell this library about the container I'm scrolling in, but the docs are pretty vague...

**Comment by sleepdeprivation** [comment]
Problem solved!

I needed to grab the actual container that was scrolling to use with `scrollTarget`, which I did with a nasty `setTimeout` hack (ie wait for 200ms until the child views load -- im sure there's a better way to do this...), and then I loaded the first 3 images, and `slice`d the container to lazy load the remaining ones.


That way the first 3 images get loaded like normal, and the lazy loaded images don't ever think they're on screen.


Thanks again for the cool plugin !

**Comment by tjoskar** [comment]
> I see them all flash really quickly ...

It sounds like you don't have set any height on the images? So the browser sets the image's height to 0 until the images are downloaded and rendered but then it is too late.

What happens if you set a height to the images? eg. `<img [lazyLoad]="image" height="500">`?

**Comment by tjoskar** [comment]
@sleepdeprivation,

> I see them all flash really quickly ...

It sounds like you don't have set any height on the images? So the browser sets the image's height to 0 until the images are downloaded and rendered but then it is too late.

What happens if you set a height to the images? eg. `<img [lazyLoad]="image" height="500">`?
