### ISSUE TITLE
Emit event when all images are loaded in View

### ISSUE THREAD

**Issue by xban1x** [tjoskar/ng-lazyload-image#190]
Would, it be possible to know when all images inside a View are loaded ? And if we know that emit an event "lazyLoadAllImagesDone" so we can for instance show a skeleton view like youtube does until all images are loaded?

**Comment by rimlin** [comment]
Hi @xban1x 
You can use [onLoad ](https://github.com/tjoskar/ng-lazyload-image#onload-optional)event for this purpose.

**Comment by xban1x** [comment]
No, this is per each image... it is a possible workaround but what i am proposing is much bigger. I wish to be able to have a service which would be Observable or a top level component which would emit an event when all children have finished loading.

**Comment by rimlin** [comment]
You can implement you own component, which will be watch for image loading status. In example:

```
@Component({
  selector: 'multiload',
  template: `
      <img
        *ngFor="let img of list;"
        [lazyLoad]="img"
        (onLoad)="onLoadImage()"
        class="ng-lazyimg"/>
  `
})
export class MultiloadComponent {
  @Input() list: Array<any>;
  num: number = 0;

  public onLoadImage() {
    this.number++;

    if (this.number >= this.list.length) {
      // all images loaded
    }
  }
}
```

**Comment by xban1x** [comment]
I have already done that. What i am proposing here is a feature for others.

**Comment by tjoskar** [comment]
Thanks for your feedback @xban1x but this requires that the lazyLoad directive is aware of other directives which it shouldn't. So the only way to implement it is to create a component (or directive) that keeps track of all images, as @rimlin suggested.

**Comment by xban1x** [comment]
As a helper it would be nice to add lazyLoadContainer directive which is aware of its lazyLoad children and emits an event once all finish loading. Thus not affecting lazyLoad component itself

**Comment by tjoskar** [comment]
I don't think this is a common use case? Or is it? If we could keep it small I'm all ears to include it to the project, by a pull request. Do you want to do it @xban1x?

**Comment by xban1x** [comment]
It would be a common use case if more developers would be creating skeleton views for waiting when data is loading.

I can make it later today yes.

**Comment by xban1x** [comment]
Re-open this so i can track it.

**Comment by tjoskar** [comment]
I will close this. I think it is better to put it in a separated lib.
