### ISSUE TITLE
offset not triggering/working

### ISSUE THREAD

**Issue by dkeulen** [tjoskar/ng-lazyload-image#192]
Hi there,

Currently i am having issues with the offset paramater.
For some reason the images do not load at the given offset.

tested in google chrome 60.0.3112.90, safari 10.1.2, firefox 51.0.1 ,
mac osx 12.12.6

According to debugging it does show that the offset value is set (to 300 in my case) when my page is loaded.

However when scrolling (window, no container) the images DO lazy load, except not at the given offset below the window, but when they enter the window (like no offset is given).

I am using latest angular/cli 1.2.7, angular 4, i don't know if this is confirmed working with this angular version.
The default image string and offset number are coming from a settings file. However the default string works and also offset is being set to the given value, but still not triggering loads.
I tested offset directly set and from variable of its component, but this does also not work.

i could provide a plunker, but that requires some setup. But basicly i am using a plain updated cli project, with the difference being that the offset is coming from a settings.ts file instead from the component (which i do have tried by the way, same problem).

![screen-offset](https://user-images.githubusercontent.com/782885/29210818-ba0e1a66-7e95-11e7-99e6-a11e0b88daa6.png)

**Comment by xban1x** [comment]
Where the value comes from should have no meaning.

I am not following this project long enough, but can offset detection be circumvented by CSS and different element positioning placing directives into separate scroll containers thus making them ignore the parent scrolling.

**Comment by dkeulen** [comment]
> I am not following this project long enough, but can offset detection be circumvented by CSS and different element positioning placing directives into separate scroll containers thus making them ignore the parent scrolling.

I tried a clean ng4 project and actually i didn't got lazyloading to work at all with the setup shown in the instructions...

**Comment by tjoskar** [comment]
@dkeulen, you are right. The offset didn't work when scrolling vertically. This bug should be fixed in version 3.2.3. Let me know if it didn't solve your issue.

**Comment by tjoskar** [comment]
And thanks for reporting this bug!

**Comment by dkeulen** [comment]
@tjoskar 

Thank you so much for looking into this issue.
I love the package so much, i was devistated that the offset was not working (primary use in my opinion).

I have tested it, and it does work, but i think it works in such a way now, that it does not seem to be meant to work this way?
This is wat i mean:

I am used to the offset being a positive number, so for example if i want an image to load 300px before entering the window, i would set offset like offset="300", but now that does not seem to work, and now i need to enter -300 a negative value.

If i keep the positive value, the image will only load 300px AFTER it has gotten INTO view...
Is this mean to work like this now?

I mean it works... but i can remember using positive values before in ng2, correct me if i am wrong.

**Comment by tjoskar** [comment]
Humm.. yeah, you are right. I will treat this as a bug and release a bug fix.

**Comment by tjoskar** [comment]
Hi @dkeulen, 
I have changed the offset after your suggestion in `3.3.1`. Try it out and let me know what you think.

**Comment by dkeulen** [comment]
Hey @tjoskar 

Seems to be working fine now! just tried it with a new project.
Thanks for the fixes!
