### ISSUE TITLE
Scroll event isn't firing on mobile

### ISSUE THREAD

**Issue by ezeikel** [tjoskar/ng-lazyload-image#195]
Works fine on desktop but scroll event doesn't fire on mobile. Any ideas why?

**Comment by tjoskar** [comment]
Hi @ezeikel,

No, not really. Scroll events should get fired on mobile as well. I just tried out the [demo site](https://tjoskar.github.io/ng-lazyload-image) in Safari on iOS and Chrome on Android and it seems to work fine.

What browser are you using on the mobile?

**Comment by tjoskar** [comment]
I just found out that that iOS do only trigger scroll event after the scrolling has completed (https://developer.mozilla.org/en-US/docs/Web/Events/scroll#iOS_UIWebView).

**Comment by matthieu80** [comment]
@tjoskar 
Hello,
In Ionic, on both android and iOS the images are not showed at the right time indeed. For example, I use lazyLoad on a display with 2 columns, filled with images. The first row of images never show on the first load, I need to scroll a little bit for them to appear.
Also, most of the time the images are displayed too late, obviously it s very apparent on a fast scroll.

**Comment by ezeikel** [comment]
It was happening on Safari and Chrome on iOS. Will test again and get back to you with the results. I'm sure when I tested the demo site I got the same results.

**Comment by florian-koenig** [comment]
I'm observing on Android (iOS seems to work), that even with a high offset value, the images are loaded way too late. Almost as if the load request is sent only when the image is already in the viewport.

**Comment by hazeem1991** [comment]
i have  the same problem here the image will not load in ionic on scroll event in do not know what happens here tried every thing no way to make it work

**Comment by tjoskar** [comment]
Is this still an issue? I'm closing this for now but let me know if you want to reopen.
