### ISSUE TITLE
Background images not working in v3.3.1

### ISSUE THREAD

**Issue by rtyx** [tjoskar/ng-lazyload-image#198]
Hi.

I don't know if it's just me, but I updated a project with the 3.3.1 version of this module and I noticed that the background mode is not working properly anymore. The style (with the right image source) and the class (ng-lazyloaded) are not being added to the div. 

I downgraded to 3.2.2 and it works correctly. Any ideas of what might be going wrong?

Thank you.

**Comment by tjoskar** [comment]
Hi,

I just tried it out and I can't reproduce it. I created this [plnkr](http://plnkr.co/edit/GRUTnu5y3C84Ivxaezyr?p=preview) and it seems to work fine. Can you give me some more information about how you are using the directive? Or update the plnkr?

**Comment by tjoskar** [comment]
Did you solve the problem? I will close this issue now but feel free to reopen it.
