### ISSUE TITLE
errors after installing ng-lazy-load

### ISSUE THREAD

**Issue by JustasKuizinas** [tjoskar/ng-lazyload-image#199]
Hi,

Any ideas why am I getting these errors?

```
in D:/Projects/~/ng-lazyload-image/src/lazyload-image.directive.js
Module not found: Error: Can't resolve 'rxjs/ReplaySubject' in 'D:\Projects\node_modules\ng-lazyload-image\src'
 @ D:/Projects/~/ng-lazyload-image/src/lazyload-image.directive.js 15:22-51
 @ D:/Projects/~/ng-lazyload-image/index.js
 @ ./Client/app/app.module.ts
 @ ./Client/app/browser-app.module.ts
 @ ./Client/main.browser.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=%2F__webpack_hmr ./Client/main.browser.ts

ERROR in D:/Projects/~/ng-lazyload-image/src/scroll-listener.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'D:\Projects\node_modules\ng-lazyload-image\src'
 @ D:/Projects/~/ng-lazyload-image/src/scroll-listener.js 7:19-45
 @ D:/Projects/~/ng-lazyload-image/src/lazyload-image.directive.js
 @ D:/Projects/~/ng-lazyload-image/index.js
 @ ./Client/app/app.module.ts
 @ ./Client/app/browser-app.module.ts
 @ ./Client/main.browser.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=%2F__webpack_hmr ./Client/main.browser.ts
```

**Comment by tjoskar** [comment]
Hi @JustasKuizinas,
If feels like something went wrong during the npm install. Can you please try to remove your `npm_modules` folder and run a npm install again?

**Comment by dkmostafa** [comment]
I got a similar error when i try to run my project using angular universal it gave me this error : 
node_modules/@angular/core/bundles/core.umd.js:501
            var /** @type {?} */ meta = Reflect$1.getOwnMetadata('propMetadata', target.constructor) || {};
                                                  ^

TypeError: Reflect$1.getOwnMetadata is not a function
    at PropDecorator

**Comment by tjoskar** [comment]
@dkmostafa, are you sure your error is related to this library? From your stack trace it looks like you have an error in `node_modules/bundles/core.umd.js`? Do you still get this error if you remove the import of `ng-lazyload-image`?

**Comment by JustasKuizinas** [comment]
Nope reinstalling doesn't help. If anyone is using angular universal and stuck with this problem I found that lazysizes works pretty good.

**Comment by tjoskar** [comment]
I will close this. Feel free to comment if somebody else got this error.
