### ISSUE TITLE
Multiple "ng-lazyloaded' class

### ISSUE THREAD

**Issue by sadriddin** [tjoskar/ng-lazyload-image#201]
Hi, 
when "lazyLoad" property is changed , "ng-lazyloaded" class has been added multiple times.
Demo here  https://embed.plnkr.co/DM6SdAzOEkrhHxeDp7Ao/

**Comment by tjoskar** [comment]
Yeah, you are right. This is a bug. It is related to this one: https://github.com/tjoskar/ng-lazyload-image/issues/187#issuecomment-324220474

**Comment by tjoskar** [comment]
I will try to fix it as soon as possible but I guess it will not happen before next week :/ 
I will however accept pull requests :)

Thanks @sadriddin for the bug report and the plnkr btw! It means a lot.

**Comment by tjoskar** [comment]
Fixed in `3.3.3`. Thanks @vaidiep
