### ISSUE TITLE
Image is not Loading in ionic

### ISSUE THREAD

**Issue by deepikajainvoloansys** [tjoskar/ng-lazyload-image#202]
when try to load image in ionic slider than it is not loading

**Comment by tjoskar** [comment]
Hi @deepikajainvoloansys, 

You have to give me more info on this :) 
How are you using `ng-lazyload-image`? Can you give me your html and js code?

**Comment by tjoskar** [comment]
Did you solve the problem? I will close this issue now but feel free to reopen it.
