### ISSUE TITLE
Web Worker Feature

### ISSUE THREAD

**Issue by NgYueHong** [tjoskar/ng-lazyload-image#205]
I am using an animated gif (3fps) as the default loading image in my ionic hybrid app. I notice that many time when the plugin is loading images, the 3fps animated gif animation become not smooth. I am thinking if the image loading can be done with web worker, could everything be much smoother, especially on low end mobile phone?

**Comment by tjoskar** [comment]
Hi

I'm currently using the global [`Image`](https://github.com/tjoskar/ng-lazyload-image/blob/998fd4954e6a992d6c4c662ee02401e489cb4545/src/lazyload-image.ts#L36-L45) class to load images. I was sure the work was being done in a separate thread (as it would be if we add a `<img src="someurl.jpg">` in the DOM (without `ng-lazyload-image`)) but I can be wrong and it may be more efficient to load the images with WebWorkers.

Are you thinking of doing something like:
```js
// Web worker
self.onmessage = function(event) {
  fetch(event.data.url)
    .then(response => response.blob())
    .then(blob => self.postMessage({ id: event.data.id, blob }));
};
```

```js
// bundle.js
const worker = new Worker(someBlobOfTheWebWorker);
worker.onmessage(event => {
  const img = getElementById(event.id);
  const url = URL.createObjectURL(event.blob);
  img.src = url;
});

// For all images:
const id = generateNewId();
element.id = id;
worker.postMessage({ id, imageUrl });
```

This is not something I want to maintain BUT I will accept PR if someone (I'm looking at you @NgYueHong but also at anyone else) wants to implement and maintain this feature.

**Comment by tjoskar** [comment]
I will close this issue now but feel free to continue the discussion.
