### ISSUE TITLE
Ionic 3 can't bind to the directive 

### ISSUE THREAD

**Issue by AbanoubNassem** [tjoskar/ng-lazyload-image#206]
I have `Ionic3` project , I have installed the plugin : `npm install ng-lazyload-image@latest --save` which is version `3.3.2` ,  I have added the `LazyLoadImageModule` to the main `AppModule` , and then tried to do this:

`<img [defaultImage]="defaultImage" [lazyLoad]="image" [offset]="offset">`

error:

```
severity: 'Error' message: 'Can't bind to 'defaultImage' since it isn't a known property of 'img'.'
severity: 'Error' message: 'Can't bind to 'lazyLoad' since it isn't a known property of 'img'.'
severity: 'Error' message: 'Can't bind to 'offset' since it isn't a known property of 'img'.'

```
then tried to add the `LazyLoadImageDirective` to the declartions of `AppModule` and the `PageModule` itself , it didn't work same errors.... what is missing here?

**Comment by tjoskar** [comment]
HI @AbanoubNassem,

I can't see anything wrong with your code. Are you register your component (that are using `LazyLoadImageDirective`) in `PageModule`as well?

**Comment by hzhu212** [comment]
It happened to me, too. Exactly the same problem.

My environment:
```
ionic version 3.19.0
ng-lazyload-image: 3.3.6
```

I had imported the `LazyLoadImageModule` into `app.module.ts`, and I got this error:
```
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'defaultImage' since it isn't a known property of 'img'. ("
  <ion-list>
    <ion-item *ngFor="let img of images">
      <img [ERROR ->][defaultImage]="defaultImage" [lazyLoad]="img" [scrollObservable]="container.ionScroll" />
    </ion-"): ng:///LazyloadPageModule/LazyloadPage.html@12:11
   ...
```

I thought it's because I forgot to declare the directive `defaultImage`. So I put `LazyLoadImageDirective` into the `declares` array of `app.module.ts`.

Then another error occured:

```
Uncaught Error: Type LazyLoadImageDirective is part of the declarations of 2 modules: LazyLoadImageModule and AppModule! Please consider moving LazyLoadImageDirective to a higher module that imports LazyLoadImageModule and AppModule. You can also create a new NgModule that exports and includes LazyLoadImageDirective then import that NgModule in LazyLoadImageModule and AppModule.
```

It seems that the `LazyLoadImageDirective` has been imported into `LazyLoadImageModule` already, so we needn't to import it manually.

So, why the `LazyLoadImageDirective` didn't work?

**Comment by tmdevde** [comment]
I have this Problem too but maybe i don't understand exactly how to use it with ionic 3. Is there a full example for ionic 3 somewhere?

**Comment by tjoskar** [comment]
@tmdevde, can you provide code snippets for how you import it and using it?
It would be even better if you could create a small git repo that I can take a look at.

**Comment by tmdevde** [comment]
I just used you hints in the readme step by step. There is no Import Error. Just the Error as the Issue Title. I will look into it with a fresh repo.

**Comment by tjoskar** [comment]
@tmdevde Did you solve your issue? If not, can you open up a new issue and link to this one?
