### ISSUE TITLE
Handling errors in loading images

### ISSUE THREAD

**Issue by matthewnewman43** [tjoskar/ng-lazyload-image#208]
I know you provide an error image field to allow a message should the image fail but is there a way to have a custom event fire when a specific error code comes back from the backend?

**Comment by tjoskar** [comment]
You can use `onLoad` to get an event when the image is loaded or when it fails.

```html
// template
<img [lazyLoad]="lazyLoadImage" (onLoad)="imageLoaded($event)">
```

```ts
// in your controller

imageLoaded(success: boolean) {
  if (success) {
    console.log('Wii');
  } else {
    console.log('No..');
  }
}
```

You will however not get the error message as it is today. We should maybe change that so the signature becomes:

```diff
-imageLoaded(success: boolean) {
+imageLoaded(error?: Error) {
```

**Comment by tjoskar** [comment]
Or maybe I misunderstood your question?

**Comment by matthewnewman43** [comment]
I'm trying to see if the error coming back is because of authentication (403). Currently the only type of data I would receive back is a boolean?

**Comment by tjoskar** [comment]
> Currently the only type of data I would receive back is a boolean?

Yeah, that is correct. 

I think it could be useful to change this behavior and also give the error object. Something like

```diff
diff --git a/src/lazyload-image.ts b/src/lazyload-image.ts
index 65a2b74..3c6237a 100644
--- a/src/lazyload-image.ts
+++ b/src/lazyload-image.ts
@@ -40,7 +40,7 @@ function loadImage(imagePath: string): Observable<HTMLImageElement> {
                 observer.complete();
             };
             img.onerror = err => {
-                observer.error(null);
+                observer.error(err);
             };
         });
 }
@@ -78,13 +78,13 @@ export function lazyLoadImage(image: HTMLElement, imagePath: string, defaultImag
             .take(1)
             .mergeMap(() => loadImage(imagePath))
             .do(() => setImage(image, imagePath))
-            .map(() => true)
-            .catch(() => {
+            .map(() => null)
+            .catch(error => {
                 if (errorImgPath) {
                     setImage(image, errorImgPath);
                 }
                 image.className += ' ng-failed-lazyloaded';
-                return Observable.of(false);
+                return Observable.of(error);
             })
             .do(() => setLoadedStyle(image));
     };
```

This will however create a breaking change. Do you have any input @rimlin?

**Comment by rimlin** [comment]
It is good idea to return error message if it thrown. Although it can break logic for current usage (after change will be `if (!err)` instead of `if (success)`), i think get error object instead of success boolean will be better.

**Comment by deanchalk** [comment]
Hi Im an Angular developer looking to get involved in some open-source projects. This is a great  project - do you still want help with this issue?

**Comment by tjoskar** [comment]
Hi @deanchalk, I would love to get a pull request for this. 
The documentation about how to set up the project is not the best right now and is something I will work on this weekend. 

In the meantime; here is a quick start guide:
1. Fork the project to your account
2. Clone the new fork from your account
3. Run `npm install` (make sure you have npm version >= 5, it is however not a big deal if you use an older version but it can result in incompatible versions)
4. `npm start` 
5. You should now be able to visit the example page on `http://localhost:9000/`
6. Do some changes and commit
7. Push to your project
8. Make a pull request

Let me know if you run into any problem :)

**Comment by deanchalk** [comment]
Cheers, will have a go this weekend 😀

**Comment by rimlin** [comment]
Is there any progress at this issue? 
@tjoskar i think error handling can be providing by append error param in `onLoad` like: `Function: (success: boolean, error: any) => void`
This case will not break the current logic of usage.

**Comment by tjoskar** [comment]
@rimlin, I like the idea of not having breaking changes but at the same time it's common (even standardize) to have the error object first and the `success` parameter is redundant since we can get the information from error object (`success = !Boolean(error)`). 

But maybe a more important question; can you pass several arguments from an `@Output`? I mean the `EventEmitter` can only handle one even at the time right?

**Comment by tjoskar** [comment]
@deanchalk, did you start working on this one? Can we help you in any way?
Otherwise, it's up for grab.

**Comment by rimlin** [comment]
@tjoskar i agree, the idea where the error object is come first is better and common usage, but now it can break logic. Current condition check about success is like: `if (success)`, but after change it will be `if (!err)`. Maybe implement this feature in major release?
Also yes, in `EventEmitter` you can only pass one param (`emit(value?: T)`).

**Comment by tjoskar** [comment]
@rimlin, Yes, it can absolutely brake some logic so this change need to be in the next major release. I do not follow any release schedule and are not afraid to do releases; we should ship a new major release whenever this is implemented.

**Comment by rimlin** [comment]
Well, if @deanchalk did not have any work at this, i will open PR with this feature at this week.

**Comment by sapierens** [comment]
When I tested around this, I was never able to extract any usable information about what caused the error, from the error object (no error codes, nothing).  
While I agree that returning an error object makes more sense, I don't really see the implementation being any more informative than it currently already is. Hence no point really  in make a breaking change, unless future-proofing in case upcoming browsers provide more information on the returned error objects?  
But I'd have to double check, maybe I was doing something wrong with the error object.

**Comment by tjoskar** [comment]
@sapierens, you are right. Sometimes you can't see the forest for the trees. Of course we can't get the status code nor the error message when we load external documents. We could use `XHR` instead of `img` but that will increase complexity and give some new problems like: `opaque` and `corse`.

@matthewnewman43, sorry. You can not get the status code from the loaded image.

@rimlin, @deanchalk, I hope you did not work too much on this issue.
