### ISSUE TITLE
images not showing

### ISSUE THREAD

**Issue by kodeine** [tjoskar/ng-lazyload-image#211]
images do not show after page scrolled.

```
<img image class="social-logo"
[errorImage]="'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM8c+buHgAIFAMzA8bS0AAAAABJRU5ErkJggg=='"                         [defaultImage]="'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM8c+buHgAIFAMzA8bS0AAAAABJRU5ErkJggg=='"
                         [lazyLoad]="'/assets/img/footer/twitter-icon.svg'">
```

**Comment by tjoskar** [comment]
@kodeine, I will need more information in order to help you :) What browser are you using? Are you using ionic? What angular version are you using? Can you see if the browser is fetching the image (twitter-icon.svg) under the network tab?

**Comment by kodeine** [comment]
@tjoskar please take a look at http://savelife-web.zzfuzrqxvs.us-east-1.elasticbeanstalk.com/users

**Comment by tjoskar** [comment]
@kodeine, the twitter icon seems to be loaded in the footer. Or am I missing something?

**Comment by kodeine** [comment]
@tjoskar ignore the footer icons, current version have regular images, but if u look at the users table, in /users/ and use the mobile version in chrome, it will not display the user images and will show the default image which is gray pixeled image.

**Comment by tjoskar** [comment]
@kodeine, did you solve the problem? I will close this issue now but feel free to reopen it.

**Comment by fradali** [comment]
Hi, 
I think I have the same problem , I'm using it into a swiper (https://github.com/fradali/ngx-swiper-wrapper-gated)
```typescript
  <swiper [config]="config" class="swiper-container">
                    <div *ngFor="let post of posts"> <!--(click)="go(VideosPage)"-->
                        <div class="video-pic">
                            <img
                                    [lazyLoad]="post.picture"
                                    [defaultImage]="'../../assets/imgs/skin/default-pic.png'"
                                    />
                            <h4><span>{{post.title}}</span></h4>
                        </div>
                    </div>
                </swiper> 
```

I only get the first image and the others it shows the default image , is there any solution? 
 thanks.
