### ISSUE TITLE
Issue after upgrade to 3.3.4

### ISSUE THREAD

**Issue by vincent-cm** [tjoskar/ng-lazyload-image#222]
Uncaught Error: Unexpected value 'LazyLoadImageModule' imported by the module 'xxxxxxParentModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.es5.js:1694)
    at compiler.es5.js:15398
    at Array.forEach (<anonymous>)

Using angular4 and probably it is only support angular5 now

**Comment by SquallX** [comment]
Hi,

I've the same issue.

**Comment by marcowenneker** [comment]
Hi,

During ng serve (Angular 4)

ERROR in Error: Metadata version mismatch for module .../node_modules/ng-lazyload-image/index.d.ts, found version 4, expected 3, resolving symbol ...

Probably same issue. Reverting back to version 3.3.3 solves problem.

**Comment by mtshare** [comment]
Same for me!

**Comment by tjoskar** [comment]
My bad. Sorry about it. 
Until I fix it, please install `3.3.3`: `npm install ng-lazyload-image@3.3.3`

**Comment by tjoskar** [comment]
> Using angular4 and probably it is only support angular5 now

Yeah, that seems to be it. @mtshare, @SquallX Are you also running Angular 4?

**Comment by brandon-tr** [comment]
Same here, and yes Angular 4

**Comment by mtshare** [comment]
> Yeah, that seems to be it. @mtshare, @SquallX Are you also running Angular 4?

Yes, I'm on Angular 4.4.4.
Downgraded to `3.3.3` currently.

**Comment by meiordac** [comment]
I had the same issue with Angular 5.

**Comment by tjoskar** [comment]
I just published `3.3.5`. It should work with Angular >= 2. Can anyone try it out and give me some feedback. Thanks.

**Comment by pcwa-ahendricks** [comment]
@tjoskar 3.3.5 fixed my issue. thx.
