### ISSUE TITLE
Angular 5 with lazyLoad property as plain string does not work

### ISSUE THREAD

**Issue by kblestarge** [tjoskar/ng-lazyload-image#223]
I just upgraded to Angular 5 and for the most part, this library works good. However I noticed that  when the lazyLoad attribute is set to a plain string, the image is never loaded.

For example, this works:
`<img id="iphone" [lazyLoad]="someRemoteImage" [offset]="-400" alt="iOS app">`
but this does not work:
`<img id="iphone" [lazyLoad]="'assets/img/sell_page/sell_page_ios_app.png'" [offset]="-400" alt="iOS app">`

What's going on here?

VERSIONS:
"ng-lazyload-image": "3.3.3",

Angular CLI: 1.5.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router
typescript: 2.6.1

**Comment by thenickfish** [comment]
I haven't experienced the same problem. For my use case this functionality is necessary.
[This plunk](https://embed.plnkr.co/LPaLeHkcSuW0ho8jIPDO/) shows it working... that said, for some reason it's loading the static image twice.

Unrelated, but it seems like plunker doesn't like the [index.js](https://unpkg.com/ng-lazyload-image@3.3.3/index.js) file, it's loading your relative links in that file respectively as... https://unpkg.com/src/lazyload-image.directive, and https://unpkg.com/src/lazyload-image.module and obviously 404'ing on those paths

I would have expected those relative paths to work. I assume it's something to do with how those files are served by the npm cdn. You could play with this plunker, and use the commented part of line 42 to see what I mean regarding the relative paths. Thanks for this library!

**Comment by tjoskar** [comment]
@kblestarge, I just created a new Angular 5 app with Angular CLI and was not able to reproduce the bug. I also created a modified version of @thenickfish plunk and it seems to work fine: https://embed.plnkr.co/rr046QU9YYWALdX7Xzf6/
Do you think you can modify the plunk or create a git repo to reproduce the error?

@thenickfish, thanks for the plunker. 
Regarding that we are loading static images twice are weird and should be treated as a bug. 

> Unrelated, but it seems like plunker doesn't like the index.js file, it's loading your relative links in that file respectively as... https://unpkg.com/src/lazyload-image.directive, and https://unpkg.com/src/lazyload-image.module and obviously 404'ing on those paths

I'm not following. Do you think this is a bug with `ng-lazyload-image` or Plunk?

**Comment by kblestarge** [comment]
It was a problem with the offset being a negative value (which didn't make sense to begin with, but a hacky solution that worked with an earlier version of this project): `[offset]="-400"`

I updated the offset to this and it worked: `[offset]="400"`.

@thenickfish and @tjoskar thanks for trying to help.

**Comment by tjoskar** [comment]
@kblestarge, Yeah, the offset was expecting a negative value some time ago but was changed to positive. Glad it works for you now.

**Comment by preservance717** [comment]
```python
<img [lazyLoad]="data?.path" [defaultImage]="defaultImage" alt="">
```
when not setting value of  **offset**,  see the above writen, operation result is:
![no-offset](https://user-images.githubusercontent.com/18299850/44500628-1e775680-a6bc-11e8-8c38-d632477ffbc2.gif)

* * *

```python
<img [lazyLoad]="data?.path" [defaultImage]="defaultImage" alt="" [offset]="100">
```
when setting value of  **offset**,  see the above writen, operation result is:
![2](https://user-images.githubusercontent.com/18299850/44500739-ad846e80-a6bc-11e8-8ecb-8520ce9ea6e2.gif)

so i  guess **offset** works, but i dont know why.
