### ISSUE TITLE
Learn semantic versioning

### ISSUE THREAD

**Issue by montella1507** [tjoskar/ng-lazyload-image#225]
Please, use semver correctly, if there is a version not compatible with angular 4, it should be version 4.x.y not 3.3.4.  (do not use "patch version").

**Comment by tjoskar** [comment]
@montella1507, 
Agree, it was never my intention to brake anything. ´3.3.4´ seams to be broken in both Angular 4 and Angular 5 (https://github.com/tjoskar/ng-lazyload-image/issues/222#issuecomment-342453038). I'm still following semver but ´3.3.4´ was a bad release.
