### ISSUE TITLE
ERROR in Metadata version mismatch

### ISSUE THREAD

**Issue by sdk4f** [tjoskar/ng-lazyload-image#227]
Hi,

I am facing the following error during the build process through webpack when using ng-lazyload-image version 3.3.5 but it's working fine with 3.3.3. Please take a look. Also, could you highlight any key differences between 3.3.3 and 3.3.5? 
 
ERROR in Metadata version mismatch for module C:/Test/LazyLoadImage/node_modules/ng-lazyload-image/src/lazyload-image.directive.d.ts, found version 4, expected 3

Thanks.

**Comment by tjoskar** [comment]
What version of Angular are you using? Especially `@angular/compiler`.

**Comment by sdk4f** [comment]
Here are the angular dependencies of my app. For now, i have locked the ng-lazyload-image version to 3.3.3 to keep the build stable.

"@angular/common": "4.1.3",
"@angular/compiler": "4.1.3",
"@angular/core": "4.1.3",
"@angular/forms": "4.1.3",
"@angular/http": "4.1.3",
"@angular/platform-browser": "4.1.3",
"@angular/platform-browser-dynamic": "4.1.3",
"@angular/router": "4.1.3", 
"@angular/upgrade": "4.1.3",
"@angular/compiler-cli": "4.1.3",
"@angular/platform-server": "4.1.3",
"ng-lazyload-image": "3.3.3",

**Comment by calvinmuller** [comment]
+1

**Comment by suhmantha1** [comment]
Having same issue. Using `@angular/compiler: 4.0`

**Comment by ehdwns980416** [comment]
+1

**Comment by oplitnik** [comment]
the same for me, works with v3.3.3 but v3.3.5 throws this error

**Comment by AlexLomm** [comment]
+1

**Comment by tjoskar** [comment]
I just releated version `3.3.6`. Let me know if you still get this error messages.
