### ISSUE TITLE
scrollObservable not working in angular 2 project

### ISSUE THREAD

**Issue by rajesh-mobicules** [tjoskar/ng-lazyload-image#229]
Hi,

scrollObservable is not working in angular2 project.

We are calling this observable but its only loading the images which are in view port properly. If we move up for the images which are already loaded those images get reset to the default one. Please suggest.

**Comment by tjoskar** [comment]
Hi, 

When you say `angular2`, do you mean you are using version 2 of Angular? Can you name your specific version?

> We are calling this observable

How are you calling the observable? Are you using the directive or are you importing some internal function from this lib? Can you give me an example how you are using it?

**Comment by tjoskar** [comment]
@rajesh-mobicules , did you solve the problem? I will close this issue now but feel free to reopen it.
