### ISSUE TITLE
Faulty isVisible logic?

### ISSUE THREAD

**Issue by sapierens** [tjoskar/ng-lazyload-image#230]
Currently the logic states that an image should be loaded when either all four sides of the image are larger than the viewport or if any of the image corners are in the viewport.
Is there any reason why images aren't loaded when any of the image's sides are in the viewport, insted of the corners?

At the moment there's a bug(?), where if an image is wider than the viewport and only its top side is visible, the image remains unloaded until the user brings any of the image's corners in the viewport or scrolls downwards, until the image is larger than the viewport. And I assume that if the image is vertically shorter than the viewport then it will only get loaded when the user scrolls horizontally to reveal any corner of the image.

Below you can see an image that shows what I mean. The default Cage image stays there until I reveal any corner or scroll downwards til it's larger than the viewport.
![rdjndlj](https://user-images.githubusercontent.com/22329727/33040778-c71ed638-ce44-11e7-908a-8a7f151db4e6.jpg)

**Comment by tjoskar** [comment]
Hi @sapierens, yes, this seems like a bug. I'm open for a PR :)
