### ISSUE TITLE
There's a way to put the lazy in a Slider?

### ISSUE THREAD

**Issue by kairovisk** [tjoskar/ng-lazyload-image#236]
Hello, i've been trying to put your lazy images inside of a slider, but the image is just replaced when the scroll event is fired, there's a trick to load the image inside of a slider?

I can provide some code if u want.

**Comment by BenHen75** [comment]
Hi, try this:

```
this.updateSearchResult = new Subject();
this.scrollSlider = Observable.merge(
    Observable.fromEvent(window, 'scroll'),
    this.updateSearchResult
);

slideChanged() {
    this.updateSearchResult.next()
}

<ion-slides (ionSlideWillChange)="slideChanged()" >
    <ion-slide>
        <img  [lazyLoad]="url" [scrollObservable]="scrollSlider"> 
    </ion-slide
</ion-slides>
```

**Comment by archangellcc** [comment]
@BenHen75 as your post,I have tried. Almost normal work, but there is a bug. 

I have 4 pictures 0 1 2 3 which is obtained form server and use *ngFor with ion-slide to show img. Finally, I get 6 ion-slide which is sorted to 3 0 1 2 3 0, the 0 1 2 3 in the middle work as expected, but when I drag the last slide or the last slide auto transform to the first slide, the img which is in the first slide don't show.

In addition, I think the follow code is similar to your post.
```<ion-slides #swiper *ngIf="slides.list.length" pager autoplay="5000"  loop="true"(ionSlideDidChange)="slideChanged()">
   <ion-slide *ngFor="let slide of slides.list">
        <img   [lazyLoad]="imageUrl" [scrollObservable]="swiper.ionSlideWillChange" [errorImage]="fallbackUrl" />
      </ion-slide>
    </ion-slides>```

**Comment by BenHen75** [comment]
yes there is a bug when loop="true" with first slide, class ng-lazyloaded isn't add to img after loop...

I will try to find a solution this week

**Comment by kairovisk** [comment]
You can close the issue, i got the idea. Thank you so much!

**Comment by tjoskar** [comment]
@BenHen75, @archangellcc do you think the `loop="true"` is an issue with this library? If so, can you open a new issue?
Thanks for your help!
