### ISSUE TITLE
The onLoad event example is flawed.

### ISSUE THREAD

**Issue by sapierens** [tjoskar/ng-lazyload-image#239]
Looks like `getBoundingClientRect()` always returns an empty rectangle (every property at 0), when the element is hidden.
This makes all the hidden elements to load their lazy images when the page initializes. And it doesn't matter how far down the page they are, since they appear to be on `X: 0, Y:0`.

While it's just an example, it's a rather misleading example.

**Comment by tjoskar** [comment]
Thanks @sapierens!
