### ISSUE TITLE
Scroll container's lazy loading is a bit off

### ISSUE THREAD

**Issue by sapierens** [tjoskar/ng-lazyload-image#241]
Currently images in scroll containers are lazy loaded based on `window` bounds. Which means that if a scroll container doesn't take up the whole screen, the image will be lazy loaded as soon as it enters `window` bounds, instead of the visible portion of scroll container.

Here's an illustrative image of what I mean:
![](https://i.imgur.com/HlveRdE.jpg)

I believe I have a solution to this, but it depends on #238 Rect implementation. So I will prepare a pull request when/if #238 gets merged.

**Comment by tjoskar** [comment]
Hi @sapierens, are you still up for the task? :)

**Comment by sapierens** [comment]
I sure am, I'll try to prepare a pull request this week.

**Comment by sapierens** [comment]
Hey @tjoskar, I've submitted a PR for this - #258. Let me know what you think.

**Comment by tjoskar** [comment]
Thanks @sapierens!
