### ISSUE TITLE
ng: Can't bind to 'lazyLoad' since it isn't a known property of 'img'

### ISSUE THREAD

**Issue by muxi2015** [tjoskar/ng-lazyload-image#251]
![](http://wx3.sinaimg.cn/mw690/9b5fc159ly1fmahej35xlj20k901t74c.jpg)
![](http://wx4.sinaimg.cn/mw690/9b5fc159ly1fmahemo3y5j20nm022dg4.jpg)
![](http://wx1.sinaimg.cn/mw690/9b5fc159ly1fmahepbh5vj20er0asmxs.jpg)
last pic:http://wx1.sinaimg.cn/mw690/9b5fc159ly1fmahepbh5vj20er0asmxs.jpg

i use ng version:5

**Comment by sapierens** [comment]
It's enough to only add `LazyLoadImageModule` under imports, no need to specify `LazyLoadImageDirective` under declarations.

Are you using SSR? If so, then make sure to include `LazyLoadImageModule` under imports in your shared app.module. Or if you don't have a shared one, then include it in both, client and server app.modules.

It's working fine for me on Angular 5.1.0

**Comment by muxi2015** [comment]
I tried to import LazyLoadImageModule results in shared.module to find that the problem was solved
thank yooooooooooou!!

**Comment by tjoskar** [comment]
Glad your problem was salved @muxi2015 

Thanks, @sapierens!
