### ISSUE TITLE
ERR_CONNECTION_REFUSED - 'ionic serve' required every time after saving new changes.

### ISSUE THREAD

**Issue by toricctan** [tjoskar/ng-lazyload-image#252]
Hi, thank you for the great work. I am not sure if it's a related issue, but every time after saving the new changes, my terminal stopped and I have to type 'ionic serve' again. 
- - - - - - - - - 
Please see the errors on terminal:
[11:05:24]  build finished in 23 ms

events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1028:11)
    at TCP.onread (net.js:572:26)

- - - - - - - - - 

Please see the errors on console:
Navigated to http://localhost:8100/
(ion-dev.js?v=3.1.0:101) WebSocket connection to 'ws://localhost:53703/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
openConnection @ ion-dev.js?v=3.1.0:101
start @ ion-dev.js?v=3.1.0:18
(anonymous) @ ion-dev.js?v=3.1.0:467
(index):39 GET http://localhost:8100/build/main.css net::ERR_CONNECTION_REFUSED
(index):48 GET http://localhost:8100/build/polyfills.js net::ERR_CONNECTION_REFUSED
(index):52 GET http://localhost:8100/build/vendor.js net::ERR_CONNECTION_REFUSED
(index):28 GET http://localhost:8100/cordova.js net::ERR_CONNECTION_REFUSED
(index):55 GET http://localhost:8100/build/main.js net::ERR_CONNECTION_REFUSED
(index):58 GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED

- - - - - - - - - 
Thank you for your time and help!

**Comment by fmendoza** [comment]
In my opinion your issue is not related to ng-lazyload-image.

**Comment by toricctan** [comment]
oh.. okay! thank you~

**Comment by tjoskar** [comment]
Hi @toricctan, I think you have some problem related to ionic and not `ng-lazyload-image`. I suggest you contact someone on their slack channel or forum: https://ionicframework.com/support

Good luck :)
