### ISSUE TITLE
Images not load due to HTTPS error

### ISSUE THREAD

**Issue by odahcam** [tjoskar/ng-lazyload-image#269]
I'm under HTTPS but the module tries to load the images trought HTTP, it causes a security error in browser.

Example: https://stackblitz.com/edit/ng-lazyload-image
 
The URL is right, but the output is wrong.

Error:

```
Mixed Content: The page at 'https://stackblitz.com/edit/angular-material-product-list-v24izo?file=app%2Flist-example.ts' was loaded over HTTPS, but requested an insecure image 'http://lorempixel.com/100/100/shop/'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by sapierens** [comment]
The link to your provided example doesn't seem to be working.

I set it up at stackblitz and the image is loading through https: https://stackblitz.com/edit/angular-yky71n?embed=1&file=app/app.component.ts

Try to set up another example.

**Comment by tjoskar** [comment]
@odahcam, Are you sure you are using `https`? eg. `http://lorempixel.com/100/100/shop/`?

**Comment by odahcam** [comment]
Can't be more sure.
![image](https://user-images.githubusercontent.com/3942006/34651738-0b49ff7c-f3bb-11e7-8b57-986911f6c8dd.png)

Also, fixed the StackBlitz link.

Before I had images without srcset working, now they are failing too, probably because of some edit and save I did unintentionally.

**Comment by tjoskar** [comment]
@odahcam, the problem seems to be `lorempixel.com`. It redirects to `http` **if** the url doesn't end with a slash (for some reason). If you go to [https://lorempixel.com/112/112/food](https://lorempixel.com/112/112/food) it will redirect to http but if you visit [https://lorempixel.com/112/112/food/](https://lorempixel.com/112/112/food/) it does not redirect you.

It seems to work fine if you just change:
```diff
- let src = `https://lorempixel.com/${spec.size}/${imgName}/ ${spec.query}`;
+ let src = `https://lorempixel.com/${spec.size}/${imgName} ${spec.query}`; 
```
and:
```diff
- return `https://lorempixel.com/112/112/${imageName}`;
+ return `https://lorempixel.com/112/112/${imageName}/`;
```

**Comment by odahcam** [comment]
Nice, thank you!

Sorry for the out-of-scope issue.

But, just to know, any idea why `ng-reflect` is different from the real `src`?

![image](https://user-images.githubusercontent.com/3942006/34653280-f0dbfcd8-f3d0-11e7-9398-ecda14a6cf3d.png)

Also, do you have any suggestion of images API for replacing lorempixel.com?
