### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by tjoskar** [tjoskar/ng-lazyload-image#270]
There are some parts that we could need some cleanup.

- [x] Mark optional Input/Output as optional (?), along with: LazyLoadImageDirectiveProps.
- [x] Extract all class names to constants (`ng-lazyloaded`, `ng-lazyloading`, `ng-failed-lazyloaded`)
- [x] Create a higher order function for `setLoadedStyle`. Right now we are setting the class names in three different ways. Normalize it (see https://github.com/tjoskar/ng-lazyload-image/pull/274#discussion_r160511311). https://github.com/tjoskar/ng-lazyload-image/blob/7b2261798a13066f23c10f353a60e636d95bad2c/src/lazyload-image.ts#L109 https://github.com/tjoskar/ng-lazyload-image/blob/7b2261798a13066f23c10f353a60e636d95bad2c/src/lazyload-image.ts#L116 https://github.com/tjoskar/ng-lazyload-image/blob/7b2261798a13066f23c10f353a60e636d95bad2c/src/lazyload-image.ts#L128
- [x] Create a function for checking if `window` is undefined. We are checking `window` in three places: https://github.com/tjoskar/ng-lazyload-image/blob/7b2261798a13066f23c10f353a60e636d95bad2c/src/lazyload-image.directive.ts#L21 https://github.com/tjoskar/ng-lazyload-image/blob/7b2261798a13066f23c10f353a60e636d95bad2c/src/lazyload-image.directive.ts#L75 https://github.com/tjoskar/ng-lazyload-image/blob/7b2261798a13066f23c10f353a60e636d95bad2c/src/scroll-listener.ts#L20
- [x] Remove `platformId` from `LazyLoadImageDirective`. This was added to detect if it was server rendered (https://github.com/tjoskar/ng-lazyload-image/commit/7140a0f8f6dea1968c32bd84b7b90ede83803ed9) but was implemented in a diffrent way later on.
- [x] Use lettable operators for rxjs instead of patching Observable, see:  https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md
- [x] Fix tslint errors, run `npx tslint -c tslint.json 'src/**/*.ts'` to get the errors
- [x] Set `"strict": true` in `tsconfig.json` and fix the errors
- [x] Set `"noImplicitAny": true` in `tsconfig.json` and fix the errors
- [x] Start using prettier and meybe remove tslint. https://github.com/prettier/prettier
- [x] Remove develop build warnings

Pull requests is more than welcome :)

**Comment by rimlin** [comment]
Cool! I will take a look for first 5 tasks at this week.
