### ISSUE TITLE
Feature request: Horizontal scrolling support

### ISSUE THREAD

**Issue by neilhem** [tjoskar/ng-lazyload-image#285]
If image is inside horizontal scrollable element image load will not be triggered on horizontal scroll

**Comment by tjoskar** [comment]
@neilhem, this should already be supported but `ng-lazyload-image` will only look for scroll events on `window` per default. Meaning if you scroll something other than window, you have to pass a reference to that dom element, something like: 

```html
<div id="my-horizontal-container">
  <img [scrollTarget]="scrollTarget" [lazyLoad]="...">
  <img [scrollTarget]="scrollTarget" [lazyLoad]="...">
  <img [scrollTarget]="scrollTarget" [lazyLoad]="...">
</div>
```
```ts
this.scrollTarget = document.getElementById('my-horizontal-container')
```

https://github.com/tjoskar/ng-lazyload-image#scrolltarget-optional

**Comment by tjoskar** [comment]
@neilhem, where you able to create a horizontal scroll?
I'm closing this for now but let me know if you can't get it to work.

**Comment by kodeine** [comment]
@tjoskar any idea how can we merge the div scroll for horizontal and window scroll for vertical?

**Comment by neilhem** [comment]
@tjoskar make it work, thx

**Comment by tjoskar** [comment]
@kodeine, you have to create your own observable in that case.

```ts
// Component
@ViewChild('wrapperdiv') wrapperDivRef: any

constructor() {
  this.scroll$ = Observable.merge(
    Observable.fromEvent(window, 'scroll'),
    Observable.fromEvent(this.wrapperDivRef, 'scroll')
  );
}
```

```html
// Template
<div #wrapperdiv>
  <img scrollObservable="scroll$" [lazyLoad]="...">
</div>
```

I'm not 100% sure about the usages of `ViewChild`. It was some time since I last used it but it should be something like that.

**Comment by tjoskar** [comment]
@neilhem, I need more information if I should be able to help you. Can you give me some example of how you are using the lib?
