### ISSUE TITLE
scrollObservable not handling async event

### ISSUE THREAD

**Issue by calbear47** [tjoskar/ng-lazyload-image#287]
Thanks again for adding the `dynamicImage | async` awhile back.  I am experiencing a new challenge that this project is very close to solving, but there's some questions I have.

I forked the project and I've been playing around with the code base. Great instructions on your contribution guide BTW! 

I am building a horizontal carousel in which there is no scrolling. I'm "scrolling" by performing a `transform: translateX(-75%)` to give the appearance that the wrapper is being scrolled. 

In light of this, I would only like to load the next image in the list, but nothing else. I am trying to pass an observable to the `[scrollObservable]` input. 

If we look at this next block of code, I only have to change one thing to achieve my desired result. This is from "lazy-load-image.directive.ts". 

```
        this.ngZone.runOutsideAngular(() => {
            let scrollObservable: Observable<Event>;
            if (this.scrollObservable) {
                scrollObservable = this.scrollObservable.startWith('');  // CHANGE HERE
            } else {
                scrollObservable = getScrollListener(this.scrollTarget || windowTarget);
            }
            this.scrollSubscription = this.propertyChanges$
                .debounceTime(10)
                .switchMap(props => scrollObservable.let(
                    lazyLoadImage(
                        this.elementRef.nativeElement,
                        props.lazyImage,
                        props.defaultImage,
                        props.errorImage,
                        props.offset,
                        props.useSrcset,
                        props.scrollTarget
                    )
                ))
                .subscribe(success => this.onLoad.emit(success));
        });

```

The only thing I need to change to the code block above is this:

This line:
```
scrollObservable = this.scrollObservable.startWith('');  

```

Becomes:

```
scrollObservable = this.scrollObservable;
```

This way, I can pass an observable like as follows and it all works fine: 

```
    ngOnInit(){
        this.testObservable = new Observable(observer => {
            const handler = () => observer.next();
            setTimeout(()=>{
                console.log("Async Event That I'm waiting for here");
                handler();
            }, 10000)
        })
    }

```

Is this a bug? Or am I missing something? Thanks for the help.

**Comment by tjoskar** [comment]
Hi @calbear47, thanks for your detailed issue.

`startWith('')` is not a bug, it's a feature 😉

The most common use case of `[scrollObservable]` is to pass an observable that observe a custom scroll, eg. `[scrollObservable]="container.myScroll"` or:
```ts
Observable.merge(
  Observable.fromEvent(window, 'scroll')
  this.someChangeSubject$
)
```

And in these cases `startWith('')` is a quite handy way to check if the image is in the viewport on initialization (before the first event).

I do, however, understand your problem. To add `startWith('')` may be a bad design decision since it gives less control to the user/developer.

In your case, is it possible to set `display: none;` when the images are hidden?

**Comment by tjoskar** [comment]
Hi @calbear47, is this still an issue or have you found a workaround?
