### ISSUE TITLE
Move the library to an organization 

### ISSUE THREAD

**Issue by tjoskar** [tjoskar/ng-lazyload-image#305]
I'm thinking of moving this library to an organization.

### Why?

Right now I'm the only owner of the library which means that I'm ultimately responsible for the library and that I have the last word. Now when this library is widely used (about 14k downloads/month) I want to share the ownership and give the contributors more power, especially since I have not used the library for some time.

I have the intention to make myself, @sapierens and @rimlin to the owner of the organization but before I do that, I want to hear your opinions (especially from @sapierens and @rimlin).

**Comment by rimlin** [comment]
I think this is not necessary, because you are good with maintain this project. But of course, if you will move this library to organization it will give more power to contributors in future.

**Comment by sapierens** [comment]
Sorry for the late response. 
I have to agree with rimlin. While I agree that it's good to give more power to contributors, I'm not really sure if it's necessary to move the library to an organization. At least for now I don't see any problems with the maintenance of the library. Although it might be a step towards better future proofing for the library.

**Comment by tjoskar** [comment]
Alright, I will keep it as it is for now 😺
