### ISSUE TITLE
errorImage and defaultImage do not work for local assets.

### ISSUE THREAD

**Issue by cjackson234** [tjoskar/ng-lazyload-image#308]
On error, I would like to display an image from the local assets directory. `'../../assets/default.png'`.

However, when I do this it errors out looking for the image and the path given is at the root of the hard drive. 

> GET file:///C:/assets/default.png net::ERR_FILE_NOT_FOUND

Is there any way to get it to pull local assets?

**Comment by tjoskar** [comment]
Hi @cjackson234,
Local assets should work fine out of the box (we do not do any url check, we just pass it to the `Img`-constructor). 
How do you start your application? Do you use any dev server or are you just open your html file in the browser without any server?

**Comment by tjoskar** [comment]
Does it work if you place a 'normal' img-tag next to the lazy loaded image, something like:
```html
<img src="../../assets/default.png">
<img [lazyLoad]="'../../assets/default.png'">
```

**Comment by cjackson234** [comment]
Correct. That's exactly what I'm seeing.

**Comment by tjoskar** [comment]
This is super weird since we only set `src` to whatever value we get: https://github.com/tjoskar/ng-lazyload-image/blob/67326f096c5aaec29543b2775a360a64e9ef4a1e/src/lazyload-image.ts#L74

These two lines should act the same:
```html
<img src="../../assets/default.png">
<img [lazyLoad]="'../../assets/default.png'" defaultImage="../../assets/default.png">
```

What does `src` have for value, if you take a look in the dev tools? Is it the same for the regular img tag as for the lazyloaded one?

**Comment by cjackson234** [comment]
> /E:/assets/default.png:1 GET file:///E:/assets/default.png net::ERR_FILE_NOT_FOUND

E:/ is the SSD root.

**Comment by cjackson234** [comment]
Found a fix:
In my component I added:
`private defaultImage = require('../../assets/default.png');`

Then in the HTML you add
` <img errorImage='{{defaultImage}}' defaultImage="{{defaultImage}}">`

and it loads just fine.

**Comment by tjoskar** [comment]
I guess it has to do with how electron is loading relative resources. 

Glad it worked for you. I'm closing this now, let me know if you want to repoen it.

**Comment by cjackson234** [comment]
It's not electron, it's webpack. When it sees a relative path it knows how to replaces it when it compiles. However, we're setting it dynamically in this case. So by the time the code compiles, the path in question no longer exists.

I would probably add a quick note in your documentation about that.

**Comment by tjoskar** [comment]
I guess it depends on the setup in that case. When I have been developing for electron I have not used webpack. 

Never the less; I agree, we should add some small note in the readme.
