### ISSUE TITLE
Feature request: Need 'onProgress' event support.

### ISSUE THREAD

**Issue by HirenParekh** [tjoskar/ng-lazyload-image#315]
It would be really nice to have 'onProgress'  event same as 'onLoad'.

I have tried to achieve functionality in my fork, but i don't know how to write test case so did't made any pull request. 

[https://github.com/HirenParekh/ng-lazyload-image](https://github.com/HirenParekh/ng-lazyload-image)

**Comment by tjoskar** [comment]
I also made a comment on a related issue: https://github.com/tjoskar/ng-lazyload-image/issues/312#issuecomment-368230015
I agree with @sapierens, XHR would bring some cool feature but also a lot of headaches, unfortunately.
