### ISSUE TITLE
Images not loading in Ionic 2 if scrollable component has percentage height.

### ISSUE THREAD

**Issue by mambrosini** [tjoskar/ng-lazyload-image#319]
Basically what the title says... the component works great unless I set the height as 100% for instance... In that case, scrolling doesn't trigger image load.

Example:
```
<div style="height: 100%; overflow-y: scroll;" #container>
    <img
        [src]="defaultImage"
        [lazyLoad]="image"
        [offset]="offset"
        [scrollTarget]="container">
</div>
```

Btw thanks for this component! it's great!

**Comment by mambrosini** [comment]
Actually my issue is related to the fact that the scrollable component wrapps a custom component which contains the lazy load image, something like:
```
<div style="height: 100%; overflow-y: scroll;" #container>
    <custom-component></custom-component>
</div>
```
The question would be, can I pass #container so that I reference it inside the custom component?
Thanks!

**Comment by tjoskar** [comment]
Hi @mambrosini,
You can pass the reference through an input variable:

 ```ts
@Component({
    selector: 'custom-component',
    template: `
        <div>
          <img
            [src]="defaultImage"
            [lazyLoad]="image"
            [offset]="offset"
            [scrollTarget]="scrollContainer">
        </div>
    `
})
export class CustomComponent {
  @Input() scrollContainer;
  ...
}
```

I'm however working on a solution where you could set a default `scrollTarget` instead of passing around a scrollTarget.

See #304, #323

**Comment by tjoskar** [comment]
Just let me know if you want to reopen the issue :)
