### ISSUE TITLE
lib not working :(

### ISSUE THREAD

**Issue by ahmedfarag2010** [tjoskar/ng-lazyload-image#326]
I found error for quotes and i handled it just like this

<img [defaultImage]="'https://media0.giphy.com/media/3oEjI6SIIHBdRxXI40/giphy.gif'" [lazyLoad]="lazyLoadImage"  [offset]="'100'"/>

and made variable for lazyload placeholder just like this

lazyLoadImage = 'http://placehold.it/500x250/000000&text=loaded%20image'; in ts file

but it still now working 
Its view the main image directly and there is no error !!

**Comment by tjoskar** [comment]
Hi,

It looks like `http://placehold.it/500x250/000000&text=loaded%20image` is returning a 404 but `https://placehold.it/500x250/000000&text=loaded%20image` is working fine.

I created a `stackblitz` where you can try it out. https://stackblitz.com/edit/ng-lazyload-image-326?file=app/app.component.html

Let me know it you have any other questions and I can reopen the issue.

**Comment by ahmedfarag2010** [comment]
Yeah .. it's working fine now

Thank you ..
