### ISSUE TITLE
Multiple scrollTargets

### ISSUE THREAD

**Issue by untitledlt** [tjoskar/ng-lazyload-image#328]
I have a horizontally scrollable div with 2 visible images and 8 lazyloaded. scrollTarget is set to that scrollable div and all images gets lazyloaded on div scroll.
The problem is that when page loads, that scrollable div is out of viewport so when i scroll down to it, first 2 visible images are not loaded as they're binded to div's scroll event which wasn't triggered yet.

Is it possible to set multiple scrollTargets (window and div) so those 2 of 8 images get lazyloaded on window scroll?

**Comment by untitledlt** [comment]
Solved this issue by attaching custom event listeners on `window` and `div` scroll events and merged them to new `[scrollObservable]`

**Comment by kodeine** [comment]
@untitledlt can you share the code you used?

**Comment by tjoskar** [comment]
@kodeine,
It was probably something like:

```ts
import { merge, fromEvent } from 'rxjs'

...

constructor() {
  this.scroll$ = merge(
    fromEvent(window, 'scroll'),
    fromEvent(someDivRef, 'scroll')
  );
}
```

```html
<img [scrollObservable]="scroll$" ... >
```

Let me know if you run into any problems.
