### ISSUE TITLE
Bug: Empty rect with an offset shouldn't be loaded

### ISSUE THREAD

**Issue by sapierens** [tjoskar/ng-lazyload-image#333]
Currently, as mentioned in #327 - if a `rect` that's returned for an image element is empty, the image will still be loaded if `offset` is greater than 0. That should not be happening since the image element at the time of checking virtually does not exist.

A simple check for an empty `rect` should be enough, I'll try to get out a PR in the coming days.

**Comment by tjoskar** [comment]
I agree, this is a bug.
