### ISSUE TITLE
How can I fetch image url from an api call when image container is in viewport?

### ISSUE THREAD

**Issue by igorissen** [tjoskar/ng-lazyload-image#338]
https://image.ibb.co/cZBbgn/Kapture_2018_04_21_at_10_59_03.gif

I have a list of shows. Each show is a component called `ShowComponent`. In each `ShowComponent` there is a `PosterComponent`. The list of shows must be displayed completely. Because of that, each `PosterComponent` are calling an API to retrieve the associated image.

Is there a way to avoid that by calling the API only when the image container is visible in the viewport? Is it possible to extend your module to do this?

**Comment by tjoskar** [comment]
I'm not sure I completely understand the problem but you want the image to be loaded when the image container (`PosterComponent`) completely visible in the viewport?

This is currently not supported. However, is it possible for you to make the API call when the image is in the viewport? Something like:

```ts
@Component({
    selector: 'poster',
    template: `
      <img
          [defaultImage]="image"
          [lazyLoad]="image"
          (onLoad)="imageIsLoaded()">
       />
    `,
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class PosterComponent {
    image = 'https://some-default-image.jpg';

    imageIsLoaded() {
      // Do the api cal and some other async work
      this.image = theRealImage;
    }
}
```

**Comment by igorissen** [comment]
> I'm not sure I completely understand the problem but you want the image to be loaded when the image container (PosterComponent) completely visible in the viewport?

Yes, it is what I wanted.

> This is currently not supported. However, is it possible for you to make the API call when the image is in the viewport?

Your code helped me a lot. Thank you.
