### ISSUE TITLE
Image Cache

### ISSUE THREAD

**Issue by sabiridwan** [tjoskar/ng-lazyload-image#340]
@tjoskar 
Thanks for the good work.
please are images cached by default ?

**Comment by tjoskar** [comment]
Hi,

`ng-lazyload-image` will not try to cache any image, however, the browser may cache the image (as it may be doing for an ordinary `img`-tag). You may be using a [service worker](https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker) if you want more granular cache control.
