### ISSUE TITLE
Ionic 3.9.2 Some Images are loaded some not

### ISSUE THREAD

**Issue by magic-77** [tjoskar/ng-lazyload-image#341]
Hi, trying to implement your Module to Lazy Load Images.
I'm using Ionic with Shopify. Therefore i catch Images from a CDN.

But i cannot get it working it should.
As you can see, the images on the right side are loaded, but not all

![image-2](https://user-images.githubusercontent.com/10066784/39267037-fd6ac7c2-48cb-11e8-9d04-329d62305275.png)

Home.html
```
<ion-content #homecontainer>
    <ion-item color="dark">
        <img src="/assets/images/myspaeti-logo@2x.png" class="home__logo">
    </ion-item>

    <ion-grid>
        <ion-row class="row__home">
            <ion-col col-6 col-sm-4 *ngFor="let item of collections" tappable (click)="openCollection(item)">
                <div class="home__category">
                    <div class="home__image">
                        <img [defaultImage]="'https://www.placecage.com/1000/1000'" [lazyLoad]="item.attrs.image.src" [offset]="offset" [scrollTarget]="homecontainer.scrollElement">
                    </div>
                    <div class="home__title">
                        {{item.attrs.title}}
                    </div>
                </div>
            </ion-col>
        </ion-row>
    </ion-grid>
</ion-content>
```

When i inspect the code i get this
Image that has been loaded
```
<img ng-reflect-lazy-image="https://cdn.shopify.com/s/file" ng-reflect-default-image="https://www.placecage.com/1000" src="https://cdn.shopify.com/s/files/1/2262/0831/collections/Susswaren_Collection.jpg?v=1524510650" class="ng-lazyloaded">
```

Image that has not been loaded
```
<img ng-reflect-lazy-image="https://cdn.shopify.com/s/file" ng-reflect-default-image="https://www.placecage.com/1000" src="https://www.placecage.com/1000/1000">
```

Do i miss something?

**Comment by tjoskar** [comment]
Can you test to use `ionScroll` instead of `scrollElement`? 
```html
<img [defaultImage]="'https://www.placecage.com/1000/1000'" [lazyLoad]="item.attrs.image.src" [offset]="offset" [scrollTarget]="homecontainer.ionScroll">
```

Does your project exist on github so I can take a look? Or is it possible for you to create a small project where you can reproduce the issue?

**Comment by magic-77** [comment]
@tjoskar Hi, i have tested both. But it does not work for me.
I have send you an Mail.

**Comment by magic-77** [comment]
After improving my app, Images are Lazy loaded now, but only after i scroll down.

**Comment by magic-77** [comment]
@tjoskar Did you found a Solution? Using "ionScroll" only fires when scrolling, so Images that are Standalone are nod loaded. Also on Home some Images gets loaded some not

**Comment by tjoskar** [comment]
@magic-77 I have not had the time to take a closer look yet. I will try to take a look at the upcoming weekend.

**Comment by magic-77** [comment]
@tjoskar Ok, thanks.

**Comment by silverio** [comment]
Same issue here, images are only lazy loaded after I scroll down. Any solution?

**Comment by mariosfx540** [comment]
Hello there, 
having the same issue here, 

```
<div #container>
    <ion-list *ngFor="let restaurant of restaurants" no-lines>
        <ion-card>
            <img [defaultImage]="'assets/imgs/download.jpeg'" 
              [lazyLoad]="[restaurant.imageUrlPath]"
              [scrollObservable]="container.ionScroll"
              [offset]="100"/>
              <ion-card-content>
                  <ion-row>
                    
                  </ion-row>
                  <ion-row>
                  </ion-row>
                </ion-card-content>
          </ion-card>
  </ion-list>
</div>
```

I'm I missing something? frist 2 Images are loaded just fine, but no more images are loaded
even when i scroll down!

Thank you!:)

**Comment by mariosfx540** [comment]
solution! 

needed to pass the content reference inside of my child component! noob staff! but it was like a charm anw!

**Comment by magic-77** [comment]
@mariosfx540 can you share your code with the solution to us?

**Comment by laislanolv** [comment]
@mariosfx540 share your solution!

**Comment by kodeine** [comment]
im facing the same solution, but i think we need to move to web-component.

**Comment by magic-77** [comment]
@tjoskar Hi, yes Problem still exists

**Comment by tjoskar** [comment]
@magic-77, I tested your code now and it seems to work if you set a proper width and height on the image.

eg. 

```diff
<div class="home__image">
-   <img [defaultImage]="defaultImage" [lazyLoad]="setImage(item)" [scrollObservable]="homecontainer.ionScroll">
+   <img width="100%" height="100%" [defaultImage]="defaultImage" [lazyLoad]="setImage(item)" [scrollObservable]="homecontainer.ionScroll">
</div>
```

I'm not total sure what the problem was but it is alwas a good idea to set a width and height on the images.

**Comment by magic-77** [comment]
@tjoskar Ok, will try this, thanks. I give you feedback asap.

**Comment by magic-77** [comment]
@tjoskar This works for me now.
