### ISSUE TITLE
ionic (3.9.2) build --prod error 

### ISSUE THREAD

**Issue by sabiridwan** [tjoskar/ng-lazyload-image#345]
hi @tjoskar 

i am having issues with ionic cordova build android --prod

the error i get is Unexpected value 'null' imported by the module 'AppModule'

when using LazyLoadImageModule.

thanks....

**Comment by tjoskar** [comment]
Hi,
What version of angular are you using? Does it work when you are building without the prod flag?

**Comment by tjoskar** [comment]
So it works to build for prod if you don't import `ng-lazyload-image`?

What version of `ng-lazyload-image` are you using? You can find out by running `npm ls ng-lazyload-image`

**Comment by shabbir-dhangot** [comment]
ng-lazyload-image version. 

    ng-lazyload-image@4.0.0

If I importing LazyLoadImageModule in app.module its building correctly. But for some of the component I need it to the share.module. 
So I added entry in shared.module and its started giving me this error while prod build.

**Comment by tjoskar** [comment]
That sound like it works when you are using `LazyLoadImageModule`? But it does not work when you are importing our own code (`shared.module`)?

**Comment by shabbir-dhangot** [comment]
Correct sir, Importing into shared.module.ts file its giving error.

**Comment by tjoskar** [comment]
Okay, I'm not sure why you are getting this error but if you are adding `LazyLoadImageModule` in the `app.module` you should be able to use the module in the whole application? Or why do you want to add it in `shared.module`?
