### ISSUE TITLE
Angular 6 having Observable issue

### ISSUE THREAD

**Issue by Manivannandurairaj** [tjoskar/ng-lazyload-image#347]
Lazyload plugin not working in angular 6 and rxjs 6.0. For more info i have attached screenshot.
![screenshot_1](https://user-images.githubusercontent.com/22704944/40094946-404ab89c-58e7-11e8-9835-f399e0d05034.png)

**Comment by tjoskar** [comment]
Hi @Manivannandurairaj,

rxjs6 introduced some breaking changes. We should update this lib to support rxjs6 but in the meantime the errors should go away if you install `rxjs-compat` (npm install rxjs-compat)

**Comment by Manivannandurairaj** [comment]
Thank you tjoskar. How i can get update once you updated rxjs6

**Comment by Manivannandurairaj** [comment]
@tjoskar I have another problem for using ng-lazyload-image plugin.
Am trying to use this plugin in ionic 3.9.2. But i got so many error, could you please to resolve this issue please.

**Comment by Manivannandurairaj** [comment]
I have created github repository and uploaded the files could you please resolve this issue.
My Repo link is : https://github.com/Manivannandurairaj/imglazyload

**Comment by tjoskar** [comment]
Hi @Manivannandurairaj,
First of all, ng-lazyload-image@4.0.0 do now use rxjs6 (and angular 6) 

Regarding your issue, I did take a look at your repo (thanks for repo) and it looks like ionic is taking a copy of the first image in the slides (for some reason) which doesn't create a new `ng-lazyload-image` instance. I'm not completely sure what is happening but if you take a look in the devtools you can see that there is a doublet of the first image and that the copy is used when the slide is looping (the original is used at the first view and if the user clicks on the first dot but the copy is used when the slide is looping). If I'm right it is not possible to solve this without changing the logic in ionic-slide :/

Can you please try to upgrade angular to version 6 and the latest version of ionic to see if the problem remians and if it does, can you create a new issue? And link to this one.

**Comment by Manivannandurairaj** [comment]
@tjoskar Thank you for your valuable time.
