### ISSUE TITLE
manully control the lazy load only fire once

### ISSUE THREAD

**Issue by johnqiuwan** [tjoskar/ng-lazyload-image#351]
How do we manully control the lazy load only fire once ?
That is, when the page go back and force, I only need lazy load images the first time the page load

**Comment by tjoskar** [comment]
You can't. If the image is removed from the dom and later on be included again; ng-lazyload-image will load the image again. But it is up to the browser if the image should be loaded so if you set cache headers on the image it should not be loaded twice.
