### ISSUE TITLE
rxjs_1.of is not a function.

### ISSUE THREAD

**Issue by husainsr** [tjoskar/ng-lazyload-image#354]
while i scrolling image up and down i got this error.

> TypeError: rxjs_1.of is not a function

How can i solve it.

**Comment by tjoskar** [comment]
What version of `ng-lazyload-image` and `rxjs` are you using? You can find out by running the following command in the terminal:
```
npm ls rxjs
```
```
npm ls ng-lazyload-image
```

**Comment by husainsr** [comment]
In `npm ls rxjs` -->empty.
In `npm ls ng-lazyload-image` --> npm ls ng-lazyload-image

**Comment by tjoskar** [comment]
ng-lazyload-image@4 only works with rxjs@6 and Angular@6 (you should see a warning about this under the installation)
https://github.com/tjoskar/ng-lazyload-image/blob/6a84744a5a1a83df643c306bde924744433bdb52/package.json#L34-L37

If you still want to use rxjs@5, you have to downgrade `ng-lazyload-image` to version: 3.4.2
You can do so by:

```
npm install ng-lazyload-image@3.4.2 --save
```
