### ISSUE TITLE
Using custom pipe instead of sync

### ISSUE THREAD

**Issue by bdairy** [tjoskar/ng-lazyload-image#357]
I am using a custom pipe to add a secure auth header to images url,, this pipe is described here in this article http://blog.jsgoupil.com/request-image-files-with-angular-2-and-an-bearer-access-token/
when the lazy loader try to fetch the image it gives me the Cannot GET /SafeValue error,, which basically related to domSanitizer..

this is my image tag

```
             <img class="employee-thumb" matListAvatar
             [lazyLoad]="'v1/photo/'+ r.employee.id | secure"
              [scrollTarget]="myScrollContainer"
              defaultImage="assets/images/loading.svg"
               [errorImage]="'assets/images/cancel.png'"
                [alt]="r.employee.name">
```
    
it is working fine when I use    a regular URL.. but when using the secure pipe it gives me Cannot Get /SafeValue must use [property]=binding

**Comment by tjoskar** [comment]
Does it work if you use a normal `img` tag?

```html
<img class="employee-thumb" matListAvatar [src]="'v1/photo/'+ r.employee.id | secure">
```

**Comment by tjoskar** [comment]
Did you solve the problem? I will close this issue now but feel free to reopen it.

**Comment by naeimsf** [comment]
Hi all. I have exactly the same problem. Does anyone know any solution? 
@bdairy Did you find any solution?
