### ISSUE TITLE
Ionic 3.0 - LazyLoad Image, Only the first image from the array was display and the rest are still using the default image? 

### ISSUE THREAD

**Issue by kapilSoni101** [tjoskar/ng-lazyload-image#360]
Hello to all ,
I have to implement the lazy load in a image it is working but there is still problem, only the first image from the array is shown after the lazy-load and the rest of the image use default image instead of the image from the array. I need help on how to fix ?
* Version : -
Angular version 2.0 
Ionic version 3.0 

`<img  [defaultImage]="userProduct.defaultImage" [lazyLoad]="userProduct?.ImageCollection[0].url"  [offset]="offset">
`

**Comment by tjoskar** [comment]
Is it possible to use intersection observer in your case?

If now, is it possible to create a small repo to reproduce the error?
