### ISSUE TITLE
How to resize images to reduce memory footprint

### ISSUE THREAD

**Issue by AndreasSchmid1** [tjoskar/ng-lazyload-image#364]
Is there an option to reduce the image dimensions to a certain value and discard the bigger image before it is rendered?

**Comment by tjoskar** [comment]
Hi,

You have two options.
1. Resize the image on the backend, before it comes to the client
2. Use the width and height attribute:
```
<img src="./some-image.jpg" height="42" width="42" />
```

Let me know if I misunderstood your question.

**Comment by AndreasSchmid1** [comment]
Hi,

1. Unfortunately server side resizing is not an option for me.
2. I think just using the width and height attriubute does not involve any image creation. The image at it  is original size is kept in memory and scaled down dynamically. In some applications this could cause a very high memory usage.

**Comment by tjoskar** [comment]
Yes, the bigger image is still in the memory but only a smaller one is rendered (if you are using width and height). If you want to resize the image on the client; I guess you should do it on a different thread (web/service worker) but I'm not sure you will get better performance, especially on devices with low CPU power.

**Comment by tjoskar** [comment]
Let me know if you find a good solution.
