### ISSUE TITLE
scrollTarget not working in mobile device

### ISSUE THREAD

**Issue by ghost** [tjoskar/ng-lazyload-image#371]
My Angular version is 7.1,  If my scroll position is outside of the initial scrollbar, the lazy load didn't work and photos will not displayed, and it should scroll horizontally. the problem is clear in the gif

![ezgif-5-57735a0ae113](https://user-images.githubusercontent.com/12588629/50888707-83cda900-140b-11e9-9c42-21fe75d55162.gif)

**Comment by morteza-gho** [comment]
I have this problem too. Did you solve the problem?

**Comment by allahyar** [comment]
Hi,
Yes , Sure . [[See here]](https://stackblitz.com/edit/ng-lazyload-image)
Tested in both modes !

**Comment by allahyar** [comment]
@tjoskar I undrestod this problem just occurred in AOT mode! what should i do?

**Comment by allahyar** [comment]
There isn't any problem on serve, Just occured on build in desktop and mobile

![2019-01-10_10-58-35](https://user-images.githubusercontent.com/12588629/50952835-e041ce80-14c6-11e9-924b-c0971462b0e8.gif)

**Comment by morteza-gho** [comment]
Hi @tjoskar  , I'm Waiting for your answer!

**Comment by tjoskar** [comment]
Is this still an issue? It seems to be fixed by using intersectionObserverPreset. Let me know if you have any problems with it or don't know how to activate it (it will be the default preset in version 7.0.0.
