### ISSUE TITLE
intersectionObserverPreset not working on build

### ISSUE THREAD

**Issue by mralienlucky** [tjoskar/ng-lazyload-image#372]
On serve intersectionObserverPreset works fine.
After build looks like he doesn't work.
You can check it on [https://payme.uz/home/payment](url)
Try to search something.

**Comment by tjoskar** [comment]
Hi @mralienlucky,
It looks like it is working fine now? Have you done any changes since you created this issue?

**Comment by mralienlucky** [comment]
Hi. No, it's not.
If you try to search, for example, `bee` it will show you this ->
[https://ibb.co/J5Zx7HC](url)

**Comment by Sufiyan8527** [comment]
I am facing the same problem, intersectionObserverPreset works fine with serve but not working on Prod. Any update on this?

**Comment by karptonite** [comment]
@tjoskar, I'm also having this issue. It seems that the problem is not between serving and production, but rather related to Ahead-of-time compilation. If I try to use the intersection observer, and run `ng serve --aot`, I get the following error:
```
ERROR in Error during template compile of 'intersectionObserverPreset'
  Complex function calls are not supported..
```
It works great without the intersection observer, so thanks for your hard work on this!

**Comment by linjie997** [comment]
Hello,
I can confirm the issue in production builds. Moreover, without intersection observe, the lazy loading doesn't seem to work on either serve or production build

**Comment by denu5** [comment]
Same here, implemented it everywhere and now some days later I found out it doesn't work with aot

**Comment by tjoskar** [comment]
This seams to be the same problem as #368, let me know if you don't agree
