### ISSUE TITLE
Image loaded twice

### ISSUE THREAD

**Issue by And-smile** [tjoskar/ng-lazyload-image#373]
Hi,
could you please help to understand if it is expected that images will be downloaded two times one by one,  if 
**cache-control**:  **no-cache, no-store, max-age=0, must-revalidate**

Reproduced also in your example:
![image](https://user-images.githubusercontent.com/9028662/51747959-a0c4d600-20b3-11e9-9307-aac52a7d73c4.png)

**Comment by tjoskar** [comment]
Hi, 

I guess this behavior is not wanted but at the same time expected.

The library is first downloading the image to see if it is available and then gives the image url to the browser how is downloading the image once again (if `no-cache, no-store, max-age=0, must-revalidate` is set).

What you could do is to create your own `[loadImage](https://github.com/tjoskar/ng-lazyload-image#hooks)` which is creating a Object url:

```ts
function loadImage({ imagePath }) {
  return await fetch(imagePath).then(res => res.blob()).then(blob => URL.createObjectURL(blob));
}
```

But this requirer same-origin request.

Another option is to not prefetch the image:
```ts
function loadImage({ imagePath }) {
  return imagePath;
}
```

But this will not trigger the error image of the image not could be loaded.

**Comment by And-smile** [comment]
Thanks for quick response,
I have tried it, result:
1. If I use this one,  I got issue
`function loadImage({ imagePath }) {
  return imagePath;
}`
![image](https://user-images.githubusercontent.com/9028662/51836985-bd0e8000-230a-11e9-8ec8-82b311570754.png)
![image](https://user-images.githubusercontent.com/9028662/51837544-5ab67f00-230c-11e9-872e-4c8e14f6485e.png)

As i understand it read my imagePath symbol by symbol, not as whole link at once. Is this also expected?
![image](https://user-images.githubusercontent.com/9028662/51837202-576ec380-230b-11e9-84fa-ff58324356c8.png)

So I tried such way:
`function loadImage({ imagePath }) {
  return [imagePath];
}` 
and it works. 

2. If use this one,
`function loadImage({ imagePath }) {
  return await fetch(imagePath).then(res => res.blob()).then(blob => URL.createObjectURL(blob));
}`
I got such result(image below),  as I understand it is also works for me
![image](https://user-images.githubusercontent.com/9028662/51837343-ccda9400-230b-11e9-954a-33cf30bf3baf.png)

**Comment by tjoskar** [comment]
That is true. A sting is iterable and RxJs vill iterated over it. We should update the code to check if it is a string or update the docs.

**Comment by tjoskar** [comment]
Thanks @And-smile for the detailed response and sorry for the delay.

**Comment by Darkligh39** [comment]
Hi, if enable in browser slow 3G, when canceled loading default image
