### ISSUE TITLE
image not show on chrome  mobile

### ISSUE THREAD

**Issue by NguyenTankpf** [tjoskar/ng-lazyload-image#379]
images do not show after scrolled. 
```
<div class="p-content-item">
<img class="img-product-item" [defaultImage]="'../../../assets/no-icon.png'" [lazyLoad]="product.ItemImageURL" [offset]="100" alt="{{product.ItemName}}"  >
</div>
```

**Comment by tjoskar** [comment]
Hi @NguyenTankpf,

> images do not show after scrolled.
1. Do you mean that the images is shown before you scroll?

2. Do you only see this problem in Chrome on mobile? Not on desktop? Not on some other browser on mobile?

3. Are you suing chrome on iOS or android?

4. How are you setting up `ng-lazyload-image`? Are you using intersection observer, like this:

```ts
LazyLoadImageModule.forRoot({
  preset: intersectionObserverPreset
})
```

**Comment by glemiere** [comment]
@tjoskar same issue here. I think it's linked to https://github.com/tjoskar/ng-lazyload-image/issues/211 but the solution provided there didn't help.

Images are not loading at all on mobile only (tried from iOS), and yeah I used intersectionObserverPreset (b/c default doesn't handle horizontal viewport detection very well)

**Comment by tjoskar** [comment]
@glemiere, Chrome on iOS is just a skin (ish) on Safari (as you may know), they are not using the Chrome's JS-engine (V8) nor Chrome's rendering engine (blink) so you will have the same feature set as Safari on iOS. iOS do however [support intersection observer](https://caniuse.com/#feat=intersectionobserver) in the latest version but I have seen that Apple roll out this feature successively. On my iPhone XS 12.2 I still have intersection observer under "Experimental WebKit Features" (Settings => Safari => Advanced => Experimental Features). 

Can you check if your phone support intersection observer? Have you used any polyfill? https://github.com/tjoskar/ng-lazyload-image/issues/387

**Comment by tjoskar** [comment]
> b/c default doesn't handle horizontal viewport detection very well
It should work as long you trigger a scroll event on the given target. Create a new issue if it does not work as you expect.

**Comment by glemiere** [comment]
@tjoskar I just disabled it when intersection observer isn't supported as a hotfix. Will spend more time into fixing this later. Sorry for no replying sooner hah, and thanks for your help :D

**Comment by tjoskar** [comment]
Is this still an issue? I'm closing this for now but feel free to open it again.
