### ISSUE TITLE
Conditional Scroll Observable

### ISSUE THREAD

**Issue by rtyx** [tjoskar/ng-lazyload-image#380]
I have a component which is used in different places, and therefore sometimes it needs a specific ```scrollObservable```, and sometimes not.

My plan is to have an input in this component to pass a ```scrollObservable``` if desired:

```@Input() scrollObservable: Observable<{} | Event>; ```

What would be the cleanest way of using this ```scrollObservable``` if provided, and the normal ```window``` scroll otherwise?

Thanks.

**Comment by tjoskar** [comment]
Hi, 

If you create a component which has an `scrollObservable`-input as below:
```ts
@Input() scrollObservable?: Observable<{} | Event>;
@Input() lazyLoadImage: string;
myDefaultImage = '/some-image.jpg'
```

and then use it:
```html
<img [defaultImage]="myDefaultImage" [lazyLoad]="lazyLoadImage" [scrollObservable]="scrollObservable" />
```

If you don't pass any `scrollObservable` to your component, the `scrollObservable` property will be `undefined` and if it is undefined `ng-lazyload-image` will use the default observable ([scroll listener](https://github.com/tjoskar/ng-lazyload-image/blob/826d6db03d6a0ad3067c1ae4de6d76761b9e5c3a/src/scroll-preset/preset.ts#L26) or [intersection observer](https://github.com/tjoskar/ng-lazyload-image/blob/826d6db03d6a0ad3067c1ae4de6d76761b9e5c3a/src/intersection-observer-preset/preset.ts#L10), depending on your setup). Did I answer your question?
