### ISSUE TITLE
Would you consider adding `window.requestIdleCallback` (or `window.requestAnimationFrame`) in a hook for final setting loaded image src?

### ISSUE THREAD

**Issue by codefactorydevelopment** [tjoskar/ng-lazyload-image#382]
https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

if yes - great!
if not - why?

nice lib, btw! ;)

**Comment by tjoskar** [comment]
Hi @codefactorydevelopment,

Can you give some background why you want to use `requestIdleCallback`?

I guess you want to do this:
```ts
window.requestIdleCallback(() => {
  element.src = imagePath;
})
```

instead of just `element.src = imagePath;`.

To call `requestAnimationFrame` or not will not make any difference, right? I mean the image will not be rendered before the next render (😉) even if we just `element.src = imagePath;`.

`requestIdleCallback` may however have some impact? Or does it? The image is already loaded so the only job left is to render. Can you elaborate on why you wants this?

**Comment by codefactorydevelopment** [comment]
hi @tjoskar,

well, when i think about it, i’d actually like to see both:

(pseudo code):

- `window.requestIdleCallback(scrollListenerHandler||observerHandler)`
- `window.requestIdleCallback(() => setSource...)`

Motivation is a broad “to stay on a safe side performance wise”.

I dont have any particular scenario where things fail using this lib (on a contrary, it works very nice) but as we know, web environment is so heterogeneous that i can imagine plethora of cases where we might want to leave the decision “what to do and when” to the browser.

Example, lets say we use `IntersectionObserver` and we have a long form. User interacts with one element on the form (list, for example) and picking one option sends him down to another list which should be preset based on previous list choice and set focus to input text right next to it and user should start typing.
At the same time, jumping to second list triggered `IntersectionObserver` and image fetch/render process. (image might be big but cached so fetch is quick but render slower)

Now, add to equation that jumping down the form can trigger many image loads.

Its this kind of scenarios where i can see `requestIdleCallback` could keep us on the safe side. Again, not to solve any particular problem  i faced but to avoid a need to think “could there be a problem”.

I hope it made sense.

**Comment by tjoskar** [comment]
I have been thinking about this and I do not think it is worth it. 
I see the use case but images have always the [lowest prioritization](https://developers.google.com/web/fundamentals/performance/resource-prioritization)(?). Further; `requestIdleCallback` is not supported in Safari (nor IE11) and `requestAnimationFrame` do not solve this issue, right?

You could also implement this by your own if you are using hooks:
```ts
import { SetLoadedImageProps, intersectionObserverPreset } from 'ng-lazyload-image';

export function setLoadedImage(args: SetLoadedImageProps) {
  requestIdleCallback(() => intersectionObserverPreset.setLoadedImage(args));
}
```

**Comment by tjoskar** [comment]
I'm closing this but if anyone wants this feature, please let me know.
