### ISSUE TITLE
Images not loading on scrolling

### ISSUE THREAD

**Issue by maxakash** [tjoskar/ng-lazyload-image#384]
I am using you your lazyloading in ionic 3 to load images . But few images are only and rest images do not load on scrolling. I am not using any reference to content.
My code 
I am importing your plugin as 
` LazyLoadImageModule.forRoot({
      preset: intersectionObserverPreset
    })`

I am using it in my app as
`  <div class="grid">
            <ion-row class="row unlimited-items">
                <ion-col col-6 class="col" *ngFor="let item of products ">
                    <ion-card tappable (click)="getProduct(item.id)">
                        <img class="image" style="height:auto;width:100%;" [defaultImage]="loadingAnimation"  [lazyLoad]="item.images[0].src">
                        <h5 *ngIf="item.name" class="card-name">{{item.name}}
                        </h5>
                        <p class="pricehtml" [innerHTML]="item.price_html"> </p>
                    </ion-card>
                </ion-col>
            </ion-row>
        </div>`
I have attached screenshot. Awaiting for your reply.

![Screen Shot 2019-04-03 at 3 31 44 PM](https://user-images.githubusercontent.com/17406944/55470630-9e3bab00-5625-11e9-9656-d71031482db7.png)

**Comment by maxakash** [comment]
Updating to ng-lazyload-image@5.1.2 and angular 7 solved the issue. Thanks for resolving .

**Comment by tjoskar** [comment]
NIce! I close this one then.
