### ISSUE TITLE
Use intersectionObserverPreset as default

### ISSUE THREAD

**Issue by tjoskar** [tjoskar/ng-lazyload-image#385]
Now when Edge, Chrome, Firefox and Safari supports `intersectionObserver` can we use it as default since it solves a lot of usual problems.

**Comment by linjie997** [comment]
I agree, for those who need to support IE can change the default implementation or import a polyfill for intersectionObserver

**Comment by felipefialho** [comment]
I agree.

**Comment by tjoskar** [comment]
`intersectionObserver` in default from version 7.0.0
