### ISSUE TITLE
IOS not loading the image on scroll with intersectionObserverPreset option

### ISSUE THREAD

**Issue by johnqiuwan** [tjoskar/ng-lazyload-image#387]
Chrome has no issues but ios device not loading the image on scroll with intersectionObserverPreset option. 

I solved the issue with 2 steps:

1. install the 'npm install intersection-observer' package
2. import 'intersection-observer' to polyfills.ts

If anyone has the same issue, you might give it a try.

**Comment by tjoskar** [comment]
It seams like Apple only have shipped intersectionObserver to some of its users (until next release). So I agree that you should include a ployfill for iOS (and IE11 if needed). 
You can also downloaded it dynamically if you don't want to include the polyfill for every user, eg.
```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CIntersectionObserverEntry"></script>
```

**Comment by tjoskar** [comment]
This is documented on the readme page. https://github.com/tjoskar/ng-lazyload-image#requirement
