### ISSUE TITLE
Ionic 4 Support

### ISSUE THREAD

**Issue by Sina7312** [tjoskar/ng-lazyload-image#388]
Hi, I just wanted to know if there is a plan to support new version of ionic (ionic 4)? thanks

**Comment by tjoskar** [comment]
Hi,
`ng-lazyload-image` have been working fine with ionic. I have not tried it with ionic 4 and to be honest; I don't really follow the developments of ionic but the goal is to support it.

Did you have any encounter any problems with inoic 4?

**Comment by Sina7312** [comment]
Thanks for your response, I did use `[scrollObservable]="container.ionScroll"` and it solved my problem. Thanks again for great library.
