### ISSUE TITLE
undefined 404	text/html	ng-lazyload-image.js:152

### ISSUE THREAD

**Issue by devendradatatech** [tjoskar/ng-lazyload-image#389]
lazy load fail to load original image due to 

undefined | 404 | text/html | ng-lazyload-image.js:152
below the code in the file and error in the bold

var /** @type {?} */ loadImage = function (_a) {
    var element = _a.element, useSrcset = _a.useSrcset, imagePath = _a.imagePath;
    var /** @type {?} */ img;
    if (isImageElement(element) && isChildOfPicture(element)) {
        var /** @type {?} */ parentClone = /** @type {?} */ (element.parentNode.cloneNode(true));
        img = parentClone.getElementsByTagName('img')[0];
        setSourcesToLazy(img);
        setImage(img, imagePath, useSrcset);
    }
    else {
        img = new Image();
        if (isImageElement(element) && element.sizes) {
            img.sizes = element.sizes;
        }
        if (useSrcset) {
            img.srcset = imagePath;
        }
        else {
            **img.src = imagePath;** error is here in the code 
        }
    }
    return Observable.create(function (observer) {
        img.onload = function () {
            observer.next(imagePath);
            observer.complete();
        };
        img.onerror = function (err) {
            observer.error(null);
        };
    });
};

**Comment by tjoskar** [comment]
Hi @devendradatatech,
I don't follow. Are you getting a 404-response when you are fetching the image? In that case the original image should not been shown, instead the error image should been shown if provided, otherwise should the default image been shown (if provided).
Are you getting any errors?

**Comment by devendradatatech** [comment]
i am not using any JSON data 

![image](https://user-images.githubusercontent.com/51471448/59186868-9d794500-8b91-11e9-8941-2baa94e62001.png)

i try u put other images then also still fine issue let me show you the class where I used other image 


componen.ts is below 
![image](https://user-images.githubusercontent.com/51471448/59186961-dfa28680-8b91-11e9-8d95-1e7ebe1b8998.png)

.hml is below
![image](https://user-images.githubusercontent.com/51471448/59186970-e630fe00-8b91-11e9-91c5-b1e612288209.png)

**Comment by tjoskar** [comment]
Okey, for some reason the image path is undefined when `ng-lazyload` tries to fetch it. Can you copy and paste your code here instead of taking screenshots? 

I tried to reproduce your issue but did not succeeded. https://codesandbox.io/s/angular-ng-lazyload-image-389-ubktv

**Comment by devendradatatech** [comment]
I had worked on the code and put the live path of other images also but not working I don't know how its failure to load.

**Comment by tjoskar** [comment]
Is the code in any repo on github that I can take a look at? Or can I visit the webbpage?

> I think its only working in the json is it?

I do not follow. What do you mean?

**Comment by devendradatatech** [comment]
https://github.com/devendradatatech/Newproject

I had applied in the 
Newproject/src/app/home component  (applied here)
Newproject/src/app/app.module.ts (lazyLoad added in the here)

please check if any issue from my side please let me know thanx for helping

**Comment by tjoskar** [comment]
I don't know how I missed it but you are using the url as a type not a value.

You should change the line:
```ts
orignelimage : "assets/images/home-banner-img.jpg";
```
to:
```ts
orignelimage = "assets/images/home-banner-img.jpg";
```

So you have something like:
```ts
export class HomeComponent {
  defaultImage = "assets/images/home-banner-img-1.jpg";
  offset = 100;
  orignelimage = "assets/images/home-banner-img.jpg";
}
```

**Comment by devendradatatech** [comment]
ok thank you so much
