### ISSUE TITLE
Template parse errors 

### ISSUE THREAD

**Issue by anuraggupta816** [tjoskar/ng-lazyload-image#392]
`<img [defaultImage]="'https://www.placecage.com/1000/1000'" [lazyLoad]="image1" >` Working 

but when I passed 
`<img [attr.defaultImage]="'https://www.placecage.com/1000/1000'" [attr.lazyLoad]="{{itemData.image[0]}}"  >`
it show Template parse errors  . 

`<img src="{{itemData.image[0]}}" >` it is working

**Comment by tjoskar** [comment]
Hi @anuraggupta816, both `defaultImage` and `lazyLoad` are properties, not attributes (the different is vague). https://angular.io/guide/template-syntax#html-attribute-vs-dom-property

That's why you cant use `[attr.defaultImage]` or `[attr.lazyLoad]`.
