### ISSUE TITLE
Add src to images on server side rendering with Universal

### ISSUE THREAD

**Issue by ebondu** [tjoskar/ng-lazyload-image#393]
Hi,

I would like to include source of images when rendering on the server side by using Universal.
The default behavior of the lib seems ignore lazy loading in this case, leaving img tags without src.
Do you have any idea to enable this ?

Thanks

**Comment by ebondu** [comment]
Here the [PR](https://github.com/tjoskar/ng-lazyload-image/pull/394) that do the job but I guess there is a better way to solve this.

**Comment by tjoskar** [comment]
Since all (?) major search boots supports javascript it should be possible to check it the client is a boot or not.
See this comment: https://github.com/tjoskar/ng-lazyload-image/pull/394#issuecomment-518189917

Let me know if I'm unclear. I'm willing to help in any way.

**Comment by tjoskar** [comment]
Included in version 7.0.0

**Comment by intellix** [comment]
You know what would be even cooler. If we assumed the page height on the server based on the user agent and only loaded the images that the browser is likely going to see (above the fold)
