### ISSUE TITLE
Could you please update angular 8

### ISSUE THREAD

**Issue by Manivannandurairaj** [tjoskar/ng-lazyload-image#400]

**Comment by tjoskar** [comment]
Don't `ng-lazyload-image` work with Angular 8 for your? What error message do you get?

**Comment by Manivannandurairaj** [comment]
When am upgrading angular 8.2.0 am facing peerdependency issue. Could you please help me. How to resolve the issue

**Comment by tjoskar** [comment]
What does the error say?

**Comment by tjoskar** [comment]
I just created a new Angular app and update Angular to version 8.2.0 and I don't get any errors/warning.

**Comment by Manivannandurairaj** [comment]
You can add and update angular/material

**Comment by tjoskar** [comment]
@Manivannandurairaj, I don't follow. Do you want me to help you update Angular to version 8.2.0 in your project or do you want me to update Angular in the angular-material project?
I do offer mentorship/consulting if that is what you are seeking.

**Comment by Manivannandurairaj** [comment]
Thank you. I have fixed this issue
