### ISSUE TITLE
Can't bind to 'lazyLoad' since it isn't a known property of 'img'

### ISSUE THREAD

**Issue by sophanith-github** [tjoskar/ng-lazyload-image#403]
![image](https://user-images.githubusercontent.com/19278390/63257747-a9296c00-c2a4-11e9-8c22-84fc52a072e7.png)

![image](https://user-images.githubusercontent.com/19278390/63257875-ec83da80-c2a4-11e9-990f-9c1785c9cd8d.png)

I imported the module in app.module.ts and app.module.ts for server already. However, the issue still occur.

I am using angular 8.

**Comment by tjoskar** [comment]
Is it possible for you to paste the code here? Or create a small repo where you can reproduce the issue?

**Comment by sophanith-github** [comment]
@tjoskar 
Maybe it's my project setting.
Importing the module in app.module.ts doesnt work for me; however, importing in the module file that i have to use lazy load works.
