### ISSUE TITLE
Can't bind to 'defaultImage' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by moises291202** [tjoskar/ng-lazyload-image#405]
I don´t know why i´m getting this error :(, here is my code:

**app.module.ts**
![image](https://user-images.githubusercontent.com/25679618/64083301-62dffe00-cce3-11e9-964c-948134af24de.png)

**example.component.ts**
![image](https://user-images.githubusercontent.com/25679618/64083325-daae2880-cce3-11e9-9013-f12ec7677e94.png)

**example.component.html**
![image](https://user-images.githubusercontent.com/25679618/64083330-05987c80-cce4-11e9-92c0-365d49fe113c.png)

Console:
![image](https://user-images.githubusercontent.com/25679618/64083337-25c83b80-cce4-11e9-8eb3-9673bc2712da.png)

**Comment by moises291202** [comment]
I imported it in the global module and in the module of my component

**Comment by tjoskar** [comment]
Hi @moises291202, 
Do you have one or multiple `@NgModule`?

**Comment by tjoskar** [comment]
@moises291202, is this still an issue for you?

**Comment by moises291202** [comment]
Yes

**Comment by tjoskar** [comment]
I can't see what is wrong and I can't reproduce it. The example page is using background images and this example as well: https://stackblitz.com/edit/angular-8-lazyload-image-intersection-observer?file=src%2Fapp%2Fapp.component.html

Is it possible for you to create a repo where you reproduce the issue or share the project?

**Comment by tjoskar** [comment]
I'm closing this now but let me know if this is still an issue for you
