### ISSUE TITLE
Lazyload does not work when scrolled horizontally (for images in slider which are not in viewport).

### ISSUE THREAD

**Issue by hinalshah91** [tjoskar/ng-lazyload-image#407]
@tjoskar When I scroll horizontally lazy loading does not work for images which are not in viewport. Can you please suggest some solution?

**Comment by chrstphrrbn** [comment]
Have you tried using the IntersectionObserver? It solved the problem for me.

https://github.com/tjoskar/ng-lazyload-image#intersectionobserver

**Comment by tjoskar** [comment]
@hinalshah91, this lib is listening on scroll events on `Window` by default. If you are scrolling horizontally you also need to tell `ng-lazyload-image` that the users are scrolling. 

The easiest way is to use [`IntersectionObserver`](https://github.com/tjoskar/ng-lazyload-image#intersectionobserver). That should solve all your problems ;) If you can't use that for some reason you could change the scroll target and create a new event stream. I can help you with that if  IntersectionObserver isn't possible.

**Comment by hinalshah91** [comment]
Doesn't work in iOS Safari mobile browser

**Comment by tjoskar** [comment]
@hinalshah91, what version of iOS are you using? Do you have included any polyfill?
https://github.com/w3c/IntersectionObserver/tree/master/polyfill or 
```html
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CIntersectionObserverEntry"></script>
```

**Comment by hinalshah91** [comment]
I am using safari 12.I.2.  I haven't included any polyfill. I will try including the script mentioned above.

**Comment by tjoskar** [comment]
It should be supported from iOS 12.2 (released 25 Mars 2019) so I guess to need to support polyfill for older versions.

**Comment by hinalshah91** [comment]
Works fine now. Thank you.
