### ISSUE TITLE
.svg images are not supporting for safari.

### ISSUE THREAD

**Issue by vinodhkumarcc** [tjoskar/ng-lazyload-image#408]
svg extension images are not updating in the view, in network tab calls are made as expected (angular 6).

**Comment by raymond-yan** [comment]
Same here. Using Angular 8 and ng-lazyload-image@6.1.0.

**Comment by nikopol-fw** [comment]
I also had the same problem in safari when i upgraded up to 6.1.0.
In 4.0.0 svg load correctly.

Angular version is 7.2.14

**Comment by tjoskar** [comment]
I have confirmed this bug in this repo: https://github.com/tjoskar/ng-lazyload-image-bugs/tree/master/408-svg-issue

I will take a look at it.
