### ISSUE TITLE
How to use ng lazy load for background images?

### ISSUE THREAD

**Issue by mc-lovin** [tjoskar/ng-lazyload-image#410]
From the documentation, there is a block which talks about background images, but the example given along with it doesn't use backgroundImage property. Can you please give an example of how it should be used ?

```ts
// Background images
// It also supports background images, by using backgroundImage:

@Component({
  selector: 'image',
  template: `
    <div [defaultImage]="defaultImage" [lazyLoad]="image"></div>
  `
})
class ImageComponent {
  defaultImage = 'https://www.placecage.com/1000/1000';
  image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
}
```

**Comment by tjoskar** [comment]
@mc-lovin, thanks for opening this issue. The documentation may be unclear but what I meant was that _after_ the image is loaded it will be assigned to [`background-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image).

So if your template looks like this: `<div [defaultImage]="defaultImage" [lazyLoad]="image"></div>`, it will first render `<div style="background-image: url('https://www.placecage.com/1000/1000')"></div>` and after the image is loaded the url will change: `<div style="background-image: url('https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg')"></div>`

Did that awnser your question?

**Comment by tjoskar** [comment]
It is done here: 
https://github.com/tjoskar/ng-lazyload-image/blob/925061b83ee9eb80a1e79b631e05ee2eb9567cc3/src/util/util.ts#L13-L24

**Comment by mc-lovin** [comment]
Makes sense. Thanks for the fast response.
