### ISSUE TITLE
Can modify refferer?

### ISSUE THREAD

**Issue by SettingDust** [tjoskar/ng-lazyload-image#422]
It seems that isn't exist a function to set the referer policy. 
Set the <img> tag reffererpolicy is useless

**Comment by tjoskar** [comment]
You are right, that is not possible right now.
What you could do is to create your own `loadImage`

```ts
export const loadImage: LoadImageFn = ({ imagePath }) => {
  const img = new Image();
  img.referrerPolicy = 'no-referrer';
  img.src = imagePath;
  return new Promise((resolve, reject) => {
    img.onload = () => resolve(imagePath);
    img.onerror = () => reject(null);
  });
};

@NgModule({
    declarations: [ AppComponent ],
    imports: [
      BrowserModule,
      LazyLoadImageModule.forRoot({ loadImage })
    ],
    bootstrap: [ AppComponent ]
})
export class MyAppModule {}
```

But what we should be doing (I think) is to clone the image so we get all the given props. I'm open for a PR (and I can help to point in the right direction)

**Comment by SettingDust** [comment]
I reslove it by meta. But it's global

**Comment by tjoskar** [comment]
@SettingDust, I'm not sure I understand. Do you want to add the `referrerpolicy` attribute on an image and it should be honored (which is reasonable)? Or do you request some other feature?

**Comment by SettingDust** [comment]
> @SettingDust, I'm not sure I understand. Do you want to add the `referrerpolicy` attribute on an image and it should be honored (which is reasonable)? Or do you request some other feature?

Yes. I want to add referrerpolicy on an image

**Comment by tjoskar** [comment]
Version `8.0.1` will honor the `referrerpolicy`.
