### ISSUE TITLE
Question on demo's animation

### ISSUE THREAD

**Issue by klishey** [tjoskar/ng-lazyload-image#423]
Quick question, are the animation on the demo like pixelated transform not included? If it is how can I use it?

**Comment by tjoskar** [comment]
No animation is included out of the box but they are quite easy to implement. 

The pixelated transform is implemented here: https://github.com/tjoskar/ng-lazyload-image/blob/master/example/src/app/pages/pixelated-image.component.ts 

In order to create a good animation, you have to create your own small pixel image.

**Comment by benjaminhorner** [comment]
I see all animations seem to be triggered by adding an .ng-lazyloaded class to the element with the mazy loaded image. However, I am failing to see where the class is added… Dos the library add the class? If so, it isn't the case in the latest release.

**Comment by tjoskar** [comment]
@benjaminhorner, I totaly mised your comment, sorry for that.

[`ng-lazyloading`](https://github.com/tjoskar/ng-lazyload-image/blob/90fd5bab2a3c336a0a938853463f656ccf946b13/src/shared-preset/preset.ts#L61) is added before the image is loaded.

[`ng-lazyloaded`](https://github.com/tjoskar/ng-lazyload-image/blob/90fd5bab2a3c336a0a938853463f656ccf946b13/src/shared-preset/preset.ts#L17) is added when the image is loaded, regardless if the image could be loaded or not.

[`ng-failed-lazyloaded`](https://github.com/tjoskar/ng-lazyload-image/blob/90fd5bab2a3c336a0a938853463f656ccf946b13/src/shared-preset/preset.ts#L52) is added when if the requested image could not be loaded. At this point will `ng-lazyloaded` also be loaded.

I will close this now but let me know if you have more questions about the animations or something else.
