### ISSUE TITLE
Can we use Skelton loading effect using CSS instead default image?

### ISSUE THREAD

**Issue by jigneshInd** [tjoskar/ng-lazyload-image#426]
Can we use Skelton loading effect using CSS instead default image?

**Comment by linjie997** [comment]
FYI I tried out using a skeleton loading effect and made it work pretty good, you need to remove the dafault image first.

Something like this should work:

```
<img class="image" [lazyLoad]="imageUrl">
```


scss:

```
@keyframes skeleton-animation {
  0% {
    background-position: -30px;
  }
  40%, 100% {
    background-position: 300px;
  }
}

.image {
  width: 250px;
  height: 130px;

    &:not(.ng-lazyloaded) {
      background-image: linear-gradient(90deg, #e8e8e8 0px, #fafafa 40px, #e8e8e8 80px);
      background-size: 600px;
      animation: skeleton-animation 1.2s ease-in-out infinite;
    }
}
```

**Comment by jigneshInd** [comment]
Is there any way to use it without any fix height width, to maintain responsiveness?

**Comment by linjie997** [comment]
@jigneshInd AFAIK there's no way to know the aspect ratio of the image before loading it.
The closest thing I can suggest is to force the image to a 16:9 aspect ratio, but you still need to specify the width of the image. To do that you can use the padding-top 56.25% trick with a container to wrap the image.
Check my codepen here: https://codepen.io/linjie997/pen/vYEQWvK

**Comment by jigneshInd** [comment]
Thanks, @linjie997, will try out it.
