### ISSUE TITLE
ng-lazyloading css class not removed

### ISSUE THREAD

**Issue by thesignal** [tjoskar/ng-lazyload-image#428]
Hi,

it seems the "ng-lazyloading" css class is not removed when "ng-lazyloaded" gets added.

My code looks like this:

`<img class="ng-lazyloading" [defaultImage]="..." [lazyLoad]="...">`

After the image (from the lazyLoad url) is loaded, "ng-lazyloaded" gets added but "ng-lazyloading" isn't removed.

I have added a stackblitz example, please tell me if this is a bug or if I'm doing something wrong. I have checked the source code and (I hope I'm not misunderstanding it) but extending the "end" function with 

`const end : FinallyFn = ({ element }) => {                                                                                                                
  removeCssClassName(element, cssClassNames.loading);
  addCssClassName(element, cssClassNames.loaded);
  };`

seems to do the trick.

[Stackblitz example](https://angular-8tyf2o.stackblitz.io)

**Comment by tjoskar** [comment]
Hi @thesignal, thanks for a detailed issue!

You are right, `ng-lazyloading` is never removed nor is it added. The lib currently only adds the css classes `ng-lazyloaded` (when the image is loaded) and `ng-failed-lazyloaded` (when the image can't be loaded).

It might be a good idea to add it between line 16 and 17: https://github.com/tjoskar/ng-lazyload-image/blob/d45e55b481dfad5fd50317bbc57b216248e554df/src/lazyload-image.ts#L16-L17 and remove it after the image is loaded. 

I accepts PRs, or I will take a look at it in a couple of days.

**Comment by tjoskar** [comment]
In version `7.1.0` the handling of css classes have been updated. Please see this section: https://github.com/tjoskar/ng-lazyload-image#css
