### ISSUE TITLE
Image is updating while scrolling, not on load page.

### ISSUE THREAD

**Issue by Riyazkhan1989** [tjoskar/ng-lazyload-image#429]
Hi Tjoskar,

First of all I have became a huge fan of yours. Thanks for providing this library.

I have implemented it as per given documents, its working fine. It also showing default image while moving to page, but my resoultion image is updating while scrolling. I want to show actual image while scrolling as well as on page load too. If i am not scrolling page then after some time it show my actual image. How I can achieve it?

**Comment by Riyazkhan1989** [comment]
?

**Comment by tjoskar** [comment]
Hi @Riyazkhan1989, 
Thanks for your kind words.

I do not really follow. Do you mean that the image is not updated until you scroll? So if you visit your webpage, the site only shows the default image until you scroll?

Is it possible to show me an example? Eather by creating a small project or if you can show me the webpage you are talking about?

**Comment by Riyazkhan1989** [comment]
Thanks for your kind response, as of now I have removed this functionality in my project as per instruction by our client. So no need to discuss more right now. But no worries I will definately contact you when I will put in my project again.

**Comment by tjoskar** [comment]
Just create a new issue if you find any new issue with this lib and I will promise to respond faster next time.
