### ISSUE TITLE
IntersectionObserver doesn't work on iOS

### ISSUE THREAD

**Issue by MIKOLAJW197** [tjoskar/ng-lazyload-image#432]
Device: iPhone 6s
Browser: Safari
Angular 8+ app hosted on firebase.

I used you package to lazy load img on some long list.

Here is screenshot:
![obraz](https://user-images.githubusercontent.com/42266201/71597083-206be800-2b42-11ea-9670-ac5d8618fb78.png)

**Comment by tjoskar** [comment]
Hi @MIKOLAJW197,
Yeah, `IntersectionObserver` was included in iOS12 (it was introduced in earlier versions but was just enabled on some devices before iOS12). [According to Apple](https://developer.apple.com/support/app-store/), only 9% of all iPhones are using iOS11 or below so it seems reasonable to add a polyfill for the last 9% (and for the IE11 users). 
I would use polyfill from polyfill.io: https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CIntersectionObserverEntry
