### ISSUE TITLE
Actual image is not loading until I  scroll + Why its load every time whenever I visit my page?

### ISSUE THREAD

**Issue by Riyazkhan1989** [tjoskar/ng-lazyload-image#433]
Hi Tjoskar,

Hope you are fine, I am here again to disturb you.
Thanks for making this great stuff for developers like us.

I am facing two problem here, may be I am missing something.

1- Initially while page loading its showing low quality image that fine, but actual image is showing when I am going to scroll page. I need this on page load. If page load then it show default low quality image then after few seconds it automatically load actual size image.

Finally, I mean that the image is not updated until I scroll? So if I visit my webpage, the site only shows the default image until I scroll?

2-  It is dependent and relative to above first problem. As per my understanding, it should not be load every time. If first time its been loaded then it will show me actual images only. See attachment. Whenever I am going to my page I need to do same step every time. Every time I need to scroll page to see actual image.

See video
[lazy_load.zip](https://github.com/tjoskar/ng-lazyload-image/files/4079988/lazy_load.zip)

**Comment by Riyazkhan1989** [comment]
I appreciate if you replay me asap. Thanks Tjoskar in advance.

**Comment by Riyazkhan1989** [comment]
This is what I am using.

`<div class="container tab-inner" [defaultImage]="lowImage" [lazyLoad]="originalImage" [backgroundImage]="lowImage ? lowImage : 'url(\'assets/images/bg_texture.png\')'"></div>`

**Comment by Riyazkhan1989** [comment]
Its fixed and working now.
OMG... I am wondered, how its possible.

In my localhost actual image is loading on while scrolling. But as I can see its working fine on my UAT server. Please explain me how thicits can be possible?

**Comment by tjoskar** [comment]
Hi @Riyazkhan1989

What version of `ng-lazyload-image` are you using? You can find the version by running: `npm ls ng-lazyload-image` in your terminal (or open `node_modules/ng-lazyload-image/package.json` and look for `version`).

Are you using `IntersectionObserver` or the `scrollPreset`? You can find out by looking the the code where you are setting up `ng-lazyload-image` in your `@NgModule`. If it looks like something like:
```ts
@NgModule({
    declarations: [ AppComponent ],
    imports: [
      BrowserModule,
      LazyLoadImageModule
    ],
    bootstrap: [ AppComponent ]
})
```
or somthing like this:

```ts
@NgModule({
    declarations: [ AppComponent ],
    imports: [
      BrowserModule,
      LazyLoadImageModule.forRoot({
        preset: scrollPreset
      })
    ],
    bootstrap: [ AppComponent ]
})
```

**Comment by Riyazkhan1989** [comment]
I am using `preset: scrollPreset`

```
@NgModule({
    declarations: [ AppComponent ],
    imports: [
      BrowserModule,
      LazyLoadImageModule.forRoot({
        preset: scrollPreset
      })
    ],
    bootstrap: [ AppComponent ]
})
```

**Comment by Riyazkhan1989** [comment]
Everything is now working well except one thing.

`<div class="container tab-inner" [defaultImage]="lowImage" [offset]="100" [lazyLoad]="originalImage" [backgroundImage]="mediumImage ? mediumImage : 'url(\'assets/images/bg_texture.png\')'">`
is above code is perfect, if  I am applying lazy load on div's background image?
How I handle background image. Its working well for my low images and HD images. But problem is that when low images showing, its not downloading HD images in back end. 

Its showing hd images as loading slowly slowly. I mean it should be show(hd images) directly as https://medium.com/ shows its images. 

Please see screenshot below how its loading my HD mages.
![showing_hd_image](https://user-images.githubusercontent.com/10295136/72700159-03d73480-3b71-11ea-8c03-5ad42fd43cc9.png)

**Comment by Riyazkhan1989** [comment]
See, I have attach my a short video, it will sure help you to understand my exact problem + I also attach what I need to achieve using this package.

I know this package is already handled but may be I am doing some silly mistake. Please check it.

[video_screenshot.zip](https://github.com/tjoskar/ng-lazyload-image/files/4084544/video_screenshot.zip)

**Comment by tjoskar** [comment]
@Riyazkhan1989, sorry for not getting back to you sooner. Is this still an issue for you?

**Comment by Riyazkhan1989** [comment]
Its fixed. Thanks for acknowledge.

**Comment by DwieDima** [comment]
@Riyazkhan1989 could you provide your solution, where your image won't load every time on page visit?
