### ISSUE TITLE
use Lazyload in video tag for poster property

### ISSUE THREAD

**Issue by shomid** [tjoskar/ng-lazyload-image#443]
I using poster property to video tag for show default image before click user on start video.<br>
I want to lazyload default image in video.<br>

```html
<video id="myVideo" controls="true" class="embed-responsive-item bg-dark" preload="none" poster="assets/images/video_preview.png">
  <source src="assets/videos/why.mp4" type="video/mp4" />
</video>
```

**Comment by tjoskar** [comment]
What are you trying to achieve?
The main reason to lazy load the image is to save bandwidth for the user and make the site faster but the `poster` will only be shown while the video is downloaded and the video is probably much larger than the poster image, and the video will be downloaded even if the poster is lazyloaded.

So the only valid reason I see to lazyload the poster is if you have a lot of small videos with different posters.

The poster is shown while loading the video but if we lazy load the poster, what should we show while loading the poster? Another image?

I think this can be done in this lib with just a small change but I'm wondering if it is worth it. I need to think about it.
