### ISSUE TITLE
twice load image in ngFor

### ISSUE THREAD

**Issue by shomid** [tjoskar/ng-lazyload-image#446]
I have a array of slider for show in carousel(ngx-bootstrap carousel).<br>
but any image twice load.<br>

    <carousel class="w-100 h-100">
      <slide *ngFor="let slider of sliderList;let i=index">
        <a [href]="slider.link" title="{{ slider.title }}">
           <img [lazyLoad]="slider.pic" class="img-fluid img-cover w-100"
          alt="{{ slider.title }}">
        </a>
      </slide>
    </carousel>

**Comment by tjoskar** [comment]
When you are saying they are loading twice, do you mean that you see the image twice in the browser or do you mean that you see that the image is loaded twice in your browsers devtool under the network tab?

Maybe related: https://github.com/tjoskar/ng-lazyload-image/issues/391#issuecomment-509931016

**Comment by shomid** [comment]
> When you are saying they are loading twice, do you mean that you see the image twice in the browser or do you mean that you see that the image is loaded twice in your browsers devtool under the network tab?
> 
> Maybe related: [#391 (comment)](https://github.com/tjoskar/ng-lazyload-image/issues/391#issuecomment-509931016)

file:///home/omid/Pictures/Screenshot%20from%202020-03-07%2020-26-19.png

**Comment by shomid** [comment]
> When you are saying they are loading twice, do you mean that you see the image twice in the browser or do you mean that you see that the image is loaded twice in your browsers devtool under the network tab?
> 
> Maybe related: [#391 (comment)](https://github.com/tjoskar/ng-lazyload-image/issues/391#issuecomment-509931016)

Notice the last 4 lines.<br>

![Screenshot from 2020-03-07 20-26-19](https://user-images.githubusercontent.com/8733354/76147625-7feef280-60b3-11ea-8490-7cce9e147f8d.png)

**Comment by tjoskar** [comment]
Yes, it looks like the images are loaded twice but it is really hard for me to say why. Is it possible for you to create a project where you can reproduce the issue? Or is it possible for me to take a look and run the code for the app you show above?

**Comment by shomid** [comment]
> Yes, it looks like the images are loaded twice but it is really hard for me to say why. Is it possible for you to create a project where you can reproduce the issue? Or is it possible for me to take a look and run the code for the app you show above?

this is project source.<br>
[project-src.zip](https://github.com/tjoskar/ng-lazyload-image/files/4302268/project-src.zip)

**Comment by shomid** [comment]
> Yes, it looks like the images are loaded twice but it is really hard for me to say why. Is it possible for you to create a project where you can reproduce the issue? Or is it possible for me to take a look and run the code for the app you show above?

Sorry for not responding too late.
[source of my project](https://drive.google.com/file/d/1njCJ84JQA7frEQrP9VONEFlIBS0P9BbN/view?usp=sharing)

**Comment by shomid** [comment]
I got here after Debug be two event are called.
first :  _start-loading_ in line 249.
second : _mount-image_ in line 250.

     tap(function () { return attributes.onStateChange.emit({ reason: 'start-loading' }); }), mergeMap(function () { return hookSet.loadImage(attributes); }), tap(function () { return attributes.onStateChange.emit({ reason: 'mount-image' }); }), tap(function (imagePath) {
            return hookSet.setLoadedImage({
                element: attributes.element,
                imagePath: imagePath,
                useSrcset: attributes.useSrcset
            });
        })

**Comment by tjoskar** [comment]
I have not been able to start your application yet (I was not able to start it through docker for some reason but I will try to install it with Vagrant instead).

I did, however, try to reproduce the issue in a smaller project: https://codesandbox.io/s/adoring-sky-hq38f Are you experiencing the same issue here?

**Comment by shomid** [comment]
> Are you experiencing the same issue here

Thank you for your attention.
this problem is only in angular universal,not exist problem in angular app(ng serve vs ng build).
no need to docker or other virtual software for start app.
in folder root project first run  `npm run build:ssr`  for build project 
then go to `dist` folder and run `node server/main.js`.

**Comment by shomid** [comment]
Can't find the cause of the problem?
This is very important to me.
Thank you very much for taking the time to find the problem.

**Comment by tjoskar** [comment]
> no need to docker or other virtual software for start app

I know, but the problem is that `npm install` is quite unsafe. It is not that I don't trust you but when I get code in a zip file on the internet I will need to use some virtual software to encapsulate the app.

I have done some digging into this and I can not reproduce this in Firefox but I can in Chrome. I still don't know why this is happening but I looked at the response header for `https://amyar24.ir/storage/container1/slide-3.jp`

and found that it returns:
```
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
```
And I tested to change that to: `Cache-Control: public` (with [this plugin](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj)) and the image was just loaded once. Is it possible for you to change the header for the images? 

Another option is to not wait for the image is loaded before updating the DOM. This can be solved by something like this:
```
// src/app/shared.module.ts

import { LazyLoadImageModule, scrollPreset } from 'ng-lazyload-image';

export function loadImage({ imagePath }: LoadImageProps) {
  return [imagePath];
}

...

LazyLoadImageModule.forRoot({
  preset: scrollPreset,
  loadImage
}),
```

**Comment by shomid** [comment]
my problem was solved with the last code snippet.
Thank you very much for your time and effort.

**Comment by Sachin-Bhola** [comment]
> > no need to docker or other virtual software for start app
> 
> I know, but the problem is that `npm install` is quite unsafe. It is not that I don't trust you but when I get code in a zip file on the internet I will need to use some virtual software to encapsulate the app.
> 
> I have done some digging into this and I can not reproduce this in Firefox but I can in Chrome. I still don't know why this is happening but I looked at the response header for `https://amyar24.ir/storage/container1/slide-3.jp`
> 
> and found that it returns:
> 
> ```
> Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
> ```
> 
> And I tested to change that to: `Cache-Control: public` (with [this plugin](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj)) and the image was just loaded once. Is it possible for you to change the header for the images?
> 
> Another option is to not wait for the image is loaded before updating the DOM. This can be solved by something like this:
> 
> ```ts
> // src/app/shared.module.ts
> 
> import { LazyLoadImageModule, scrollPreset } from 'ng-lazyload-image';
> 
> export function loadImage({ imagePath }: LoadImageProps) {
>   return [imagePath];
> }
> 
> ...
> 
> LazyLoadImageModule.forRoot({
>   preset: scrollPreset,
>   loadImage
> }),
> ```

In the latest version, LazyLoadImageModule doesn't have forRoot and without the above, I am getting the same issue if cache is disabled. Is there have any other solution for this?

**Comment by tjoskar** [comment]
Hi @Sachin-Bhola
It would be super helpful if you could create a new issue with more details. 
Preferably with a small repo/stackblitz where you can reproduce the issue. Let me know if you need help to setup a [stackblitz](https://stackblitz.com/) repo.
