### ISSUE TITLE
Does not load all images 

### ISSUE THREAD

**Issue by jhayg12** [tjoskar/ng-lazyload-image#448]
I have a scenario wherein the other images where not been loaded and it only shows the [defaultImage]

The images where coming from the service.

**Comment by tjoskar** [comment]
Hi,

Are you using the default (IntersectionObserver) preset or the scroll preset? Are the images that are not loaded in the viewport after the page load or do you have to scroll/changing tab/page?

Can you provide a small example app where you can reproduce the issue?

**Comment by jhayg12** [comment]
Hi @tjoskar 

What I have been currently using is the scroll preset and when I changed it today to default (IntersectionObserver) it works well as expected the images are been loaded successfully.

Unfortunately I cant give a small app for this one cause I am on a tight schedule for the whole week.

**Comment by tjoskar** [comment]
Does it work for you with the IntersectionObserver-preset? If that is the case, can I close this issue?

There are tons of edge cases you have to think of when you are using the scroll-observer. Like: the DOM needs to be ready before this directive starts and that you are scrolling in the right container. So I would recommend all to use the IntersectionObserver-preset.

**Comment by rsivan** [comment]
My use case involves Intersection-Observer-preset: I have an ngFor for my thumbs into an array which becomes populated AFTER the parent div is visible. As a result the top scroll images are never loaded, but the next ones, on scrolling down, start appearing as expected.
