### ISSUE TITLE
It Should have ability to pass a element ref until Image Is loaded A different SVG is Appended after Image Is loaded  The Div Should be Removed and Image  Should be Appended

### ISSUE THREAD

**Issue by akashthakur05** [tjoskar/ng-lazyload-image#453]
- Pass The Component /or ref   To   div to be appended 

[Advatages]:
 
-   This. The lazy load can serve as COntent Preloader  passing an SVG  or some div

**Comment by tjoskar** [comment]
Hi,
I'm not sure what you mean. Do you want to include a ref to a dom element instead of an image?
Somthing like:
```html
<img [defaultElement]="aRef" [lazyLoad]="image">
```

And then show the ref until the image has been loaded? 

Regarding svg, that is already supported:
```html
<img [defaultImage]="path/to/image.svg" [lazyLoad]="image">
``` 

Can you show me an example of the api you are thinking of?

**Comment by akashthakur05** [comment]
@tjoskar  First of All Thankyou For Taking in Attention.

Yes you got It Right    about this one 
 > <img [defaultElement]="aRef" [lazyLoad]="image">

Regarding svg, that is already supported:

`If You Could Provide The Support for HTML DOM element ` it Would be Best in Many cases like providing the reference to `canvas` element or some `svg` `DOM` element 

<img [defaultImage]="path/to/image.svg" [lazyLoad]="image">


> My example is as Follow 

><any-xyz-elemtn. {ref}>


><img [defaultElement]="ref" [lazyLoad]="image">

**Comment by tjoskar** [comment]
I'm not sure how to solve this.
Should the canvas replace the image until the image is loaded? Because that is quite difficult. Maybe that is could be possible to place the canvas as a child to a div.

Something like this: (should be possible in `8.0.0-beta.2`):
```html
<canvas id="mycanvas"></canvas>

<div [lazyLoad]="image" data-defaultcanvasid="mycanvas"></div>
```

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { LazyLoadImageModule, IntersectionObserverHooks, Attributes } from 'ng-lazyload-image';
import { AppComponent } from './app.component';

class LazyLoadImageHooks extends IntersectionObserverHooks {
  setup(attributes: Attributes) {
    const canvasId = attributes.element.dataset.defaultcanvasid;
    const canvas = document.getElementById(canvasId).cloneNode(true);
    attributes.element.appendChild(canvas);
  }
  finally(attributes: Attributes) {
    attributes.element.innerHTML = '';
  }
}

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, LazyLoadImageModule.forRoot(LazyLoadImageHooks)],
  bootstrap: [AppComponent],
})
export class MyAppModule {}
```
