### ISSUE TITLE
IntersectionObserver is undefined on IE11

### ISSUE THREAD

**Issue by martinduris** [tjoskar/ng-lazyload-image#454]
Hi,
i am using ng-lazyload-image (v. 7.1.0) with angular (v. 9.1.0) but on IE11 i see error:
'IntersectionObserver' is undefined.
(you can try here: https://www.besmarthead.com/business)

any ideas how to fix it ?
Thanks a lot
Martin

**Comment by philippfo9** [comment]
Include the polyfill?

https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by tjoskar** [comment]
Yeah, you will need to include polyfill for `IntersectionObserver` if you need to support IE. You will also need polyfill for `WeakMap` and `String.prototype.includes`. See: https://github.com/tjoskar/ng-lazyload-image#-prerequisites-

The easiest way is to get it from https://polyfill.io/v3/url-builder/
Aka: include the following line:
https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver%2CIntersectionObserverEntry%2CString.prototype.includes%2CWeakMap

**Comment by martinduris** [comment]
Hi,
thanks for help. Add of polyfill helps.
Martin
