### ISSUE TITLE
Angular 8 with enableivy true gives error

### ISSUE THREAD

**Issue by kinimatt** [tjoskar/ng-lazyload-image#455]
ERROR in No suitable injection token for parameter 'el' of class 'LazyLoadImageDirective'.
no type or decorator

Angular CLI: 8.3.25
Angular: 8.2.14
Node: 10.15.1
OS: win32 x64

**Comment by tjoskar** [comment]
Hi, 
I can not reproduce this issue. I have tested in both Angular 8 and 9 without any problems. Is it possible four you to create a small repo where you can reproduce the issue?

**Comment by tjoskar** [comment]
I need more information to be able to help you. I will close this now but be free to write a comment and I will open it again.
