### ISSUE TITLE
It would be nice to have an option to debounce

### ISSUE THREAD

**Issue by rsivan** [tjoskar/ng-lazyload-image#456]
My use case is a fast scroll from top to bottom.
It would be nice to skip loading all the images in between.

Thanks.

**Comment by tjoskar** [comment]
I agree. I will take a look.

**Comment by tjoskar** [comment]
This should be possible in the upcoming version `8.0.0-beta.1` (`npm install ng-lazyload-image@8.0.0-beta.1`). Please try it out and get back to me with what you think.

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { debounceTime } from 'rxjs/operators';
import { LazyLoadImageModule, IntersectionObserverHooks, Attributes } from 'ng-lazyload-image';
import { AppComponent } from './app.component';

class LazyLoadImageHooks extends IntersectionObserverHooks {
  getObservable(attributes: Attributes) {
    return super.getObservable(attributes).pipe(debounceTime(1000))
  }
}

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, LazyLoadImageModule.forRoot(LazyLoadImageHooks)],
  bootstrap: [AppComponent],
})
export class MyAppModule {}
```

Let me know if something is unclear or if it doesn't work for you. The plan is to leave the beta channel in a couple of days.

**Comment by tjoskar** [comment]
I have created a sandbox here where you can try it out: https://codesandbox.io/s/lazy-load-image-with-httpclient-to538?file=/src/app/app.module.ts

Scroll down fast and then slowly up

**Comment by tjoskar** [comment]
Version 8.0.0 is now out.
Let me know if you have any issues or if it does not solve your issue.

**Comment by MaherNajar** [comment]
Property 'forRoot' does not exist on type 'typeof LazyLoadImageModule'
