### ISSUE TITLE
cdk-virtual-scroll-viewport , image not reloaded

### ISSUE THREAD

**Issue by reatailret** [tjoskar/ng-lazyload-image#457]
I am load 5 random images, from placeholder services. Random urls, two services. After scroll, new 5 items added , old components reused, labels changed, image src [lazyload] changed, but images not. In console only "reason : setup", no "finally" and other. 
If I use scroll preset and custom observable images changed, but not loaded on first step (showed default image), because no scrolling events.

**Comment by tjoskar** [comment]
Did you solve the issue?

**Comment by reatailret** [comment]
> 
> 
> Did you solve the issue?

No. I thought and decided that the virtual scrolling does not need lazyloading. Because it already works like a lazyload. But it would be convenient if there was an option "forceload", which would download the image immediately, when "src" set (and with showing default image).

**Comment by pascalbayer** [comment]
Having the same issue. Is there any workaround as suggested by @reatailret with a forceload attribute?

**Comment by tjoskar** [comment]
Is it possible to create a small project where you reproduce the issue?

**Comment by ClemensSchneider** [comment]
See #473 for additional details and a reproduction of the issue.
