### ISSUE TITLE
Hooks cannot add through a service

### ISSUE THREAD

**Issue by damithmalalanayake** [tjoskar/ng-lazyload-image#459]
I have an issue with hooks since I cannot add a hook through a service. Is there any way of doing that by injecting this method through a service?

function loadImage({ imagePath }: LoadImageProps): Promise<string> {
  return await fetch(imagePath, {
    headers: {
      Authorization: 'Bearer ...'
    }
  }).then(res => res.blob()).then(blob => URL.createObjectURL(blob));
}
 
@NgModule({
    declarations: [ AppComponent ],
    imports: [
      BrowserModule,
      LazyLoadImageModule.forRoot({ loadImage })
    ],
    bootstrap: [ AppComponent ]
})
export class MyAppModule {}

**Comment by tjoskar** [comment]
Hi,

I'm not sure what you are asking. Do you want to do something like (this is currently **not** supported but I'm consider it):

```ts
export class LazyloadImageHooks {

  constructor(private http: HttpClient, private logger: Logger) { }

  loadImage({ imagePath }: LoadImageProps) {
    this.logger.log('Load the image');
    return this.http.get(imagePath);
  }
}
```

**Comment by damithmalalanayake** [comment]
Yeah. This is what I exactly want. Thanks for the consideration.

**Comment by tjoskar** [comment]
This should now be possible in the upcoming release. I would be grateful if you could try it out and see what you think. 

You can install it by `npm install ng-lazyload-image@8.0.0-beta.1` and then in your module:

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { LazyLoadImageModule, IntersectionObserverHooks, Attributes } from 'ng-lazyload-image';
import { AppComponent } from './app.component';

class LazyLoadImageHooks extends IntersectionObserverHooks {
  private http: HttpClient;

  constructor(http: HttpClient) { // You can inject what ever service you want here
    super();
    this.http = http;
  }

  loadImage({ imagePath }: Attributes): Promise<string> {
    return this.http.get(imagePath, {
      responseType: 'blob',
      headers: { Authorization: 'Bearer ...' },
    }).pipe(map(blob => URL.createObjectURL(blob)));
  }
}

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, LazyLoadImageModule.forRoot(LazyLoadImageHooks, [HttpClient])], // You must add the dependency list here, eg. the same dependency you inject in `LazyLoadImageHooks`.
  bootstrap: [AppComponent],
})
export class MyAppModule {}
```

There are some examples here: https://github.com/tjoskar/ng-lazyload-image/tree/beta#-hooks-

Let me know if something is unclear or if it doesn't work for you. The plan is to leave the beta channel in a couple of days.

**Comment by damithmalalanayake** [comment]
Sure. I'll try it out. Thanks!

**Comment by tjoskar** [comment]
I just found a type issue so I published `ng-lazyload-image@8.0.0-beta.2`

**Comment by damithmalalanayake** [comment]
I got an error saying that "ng-lazyload-image has no exported member 'IntersectionObserverHooks'. Did you mean 'intersectionObserverPreset'?" in Intellij but the images are perfectly loading. I hope you could fix this error. Thanks!

**Comment by tjoskar** [comment]
I believe your IDE is out of sync. Can you try to restart Intellij to see if the error disappears?

**Comment by damithmalalanayake** [comment]
Yeah, that was the problem. Thanks. Another thing it is better if we could move this hook to a different file.  
Thanks for the immediate fix.

**Comment by tjoskar** [comment]
FYI: I created a simple example here: https://codesandbox.io/s/lazy-load-image-with-httpclient-68785?file=/src/app/app.module.ts

> Another thing it is better if we could move this hook to a different file.

What do you mean? Do you want to import it from a different path like:
```ts
import { IntersectionObserverHooks } from 'ng-lazyload-image/hooks';
```
Or do you mean that you want to put you `LazyloadImageHooks` in a different file?

**Comment by damithmalalanayake** [comment]
I want to put LazyloadImageHook to a different file.

**Comment by tjoskar** [comment]
You can place it in what file you want :) I agree that you should not put it in the same file as your app module but that is up to you.

**Comment by damithmalalanayake** [comment]
Yep. It worked. My mistake. Thanks, buddy!
