### ISSUE TITLE
[Issue] Hooks "Setup" ineffective 

### ISSUE THREAD

**Issue by lucebert** [tjoskar/ng-lazyload-image#460]
Hello,

I am encountering an issue when I try to override the `setup` function. 
What I want to do is to add the same default image for all images of my website, 
so here is my code : 

```
function setup(atter: Attributes) {
  atter.defaultImagePath = "/path/to/default.png";
}

@NgModule({
    declarations: [ AppComponent ],
    imports: [
      BrowserModule,
      LazyLoadImageModule.forRoot({ setup })
    ],
    bootstrap: [ AppComponent ]
})
export class MyAppModule {}
```

When i am doing this, the result is there is no default image, but i got the alt text of the image before loading.

I noticed that the default image does not appear even if i implement `setup` with only a console.log() like this : 
```
function setup(atter: Attributes) {
  console.log(atter);
}
```
and an image like this : 
```
@Component({
  selector: 'image',
  template: `
    <img [defaultImage]="defaultImage" [lazyLoad]="image">
  `
})
class ImageComponent {
  defaultImage = 'https://www.placecage.com/1000/1000';
  image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
}
```
If i remove the `setup` override on app module, the default image reappears.

Is this a bug or do I something wrong ?

Thanks !

ng-lazyload-image: v7.1.0
node version : v12.16.3
npm version : v6.14.4
angular : 
@angular-devkit/architect         0.1000.0-next.6
@angular-devkit/build-angular     0.1000.0-next.6
@angular-devkit/build-optimizer   0.1000.0-next.6
@angular-devkit/build-webpack     0.1000.0-next.6
@angular-devkit/core              10.0.0-next.6
@angular-devkit/schematics        10.0.0-next.6
@angular/cdk                      8.2.3
@angular/cli                      10.0.0-next.6
@angular/localize                 9.1.9
@angular/material                 8.2.3
@ngtools/webpack                  10.0.0-next.6
@schematics/angular               10.0.0-next.6
@schematics/update                0.1000.0-next.6
rxjs                              6.5.5
typescript                        3.9.3
webpack                           4.43.0

**Comment by tjoskar** [comment]
Hi,

Interesting use case. I should not mark this as a bug but at the same time it is nothing that is currently supported.

When you add the `setup` hook, you also overwrite the default `setup` hook, and it is the default `setup` hook that sets the default image. I'm thinking of adding a `beforeSetup` witch should solve your issue.

What you can do today is to call the setup function in your hook:
```ts
import { LazyLoadImageModule, Attributes, intersectionObserverPreset } from 'ng-lazyload-image';

export function setup(atter: Attributes) {
  atter.defaultImagePath = "/path/to/default.png";
  intersectionObserverPreset.setup(atter);
}

@NgModule({
    declarations: [ AppComponent ],
    imports: [
      BrowserModule,
      LazyLoadImageModule.forRoot({ setup })
    ],
    bootstrap: [ AppComponent ]
})
export class MyAppModule {}
```

**Comment by lucebert** [comment]
Thanks for your reply,

Effectively it works like a charm with this. I doubted that my issue was due to something like this but I didn't realize that I could call intersectionObserverPreset.setup(). Maybe you should add this information in the README's hooks part to make it clear for everyone.

A `beforeSetup` function should works but at the same time I need, in my use case, to change CSS default image at the setup and modify it again in the finally function. So I have to override the finally function (and understand how the default proceeds), or need a `beforeFinaly` function too. However, for me, the solution you told me about is good and it's okay to call the original default function.

**Comment by tjoskar** [comment]
I have updated the docs in the upcoming version and made it a bit more clear. 

In version `8.0.0-beta.2`, the hooks should be in a class container instead so you have something like:

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule, HttpClient } from '@angular/common/http';
import { LazyLoadImageModule, IntersectionObserverHooks, Attributes } from 'ng-lazyload-image';
import { AppComponent } from './app.component';

class LazyLoadImageHooks extends IntersectionObserverHooks {
  setup(atter: Attributes) {
    atter.defaultImagePath = "/path/to/default.png";
    return super.setup(atter);
  }
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpClientModule,
    LazyLoadImageModule.forRoot(LazyLoadImageHooks)
  ],
  bootstrap: [AppComponent],
})
export class MyAppModule {}
```

Let me know if something is unclear or if it doesn't work for you. The plan is to leave the beta channel in a couple of days.

**Comment by lucebert** [comment]
It's better like that, I understand quite well. I will let you know if I have any problems. Thanks
