### ISSUE TITLE
点击显示弹窗后，下面的图片也不显示了

### ISSUE THREAD

**Issue by webstermobile** [tjoskar/ng-lazyload-image#464]
有弹窗弹出来的时候，页面上的图片就消失了，
另外，和cdk virtual scroll 一起使用的时候，也经常出现图片不显示的情况；

**Comment by tjoskar** [comment]
I used [google translate](https://translate.google.se/#view=home&op=translate&sl=auto&tl=en&text=%E6%9C%89%E5%BC%B9%E7%AA%97%E5%BC%B9%E5%87%BA%E6%9D%A5%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E9%A1%B5%E9%9D%A2%E4%B8%8A%E7%9A%84%E5%9B%BE%E7%89%87%E5%B0%B1%E6%B6%88%E5%A4%B1%E4%BA%86%EF%BC%8C%0A%E5%8F%A6%E5%A4%96%EF%BC%8C%E5%92%8Ccdk%20virtual%20scroll%20%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8%E7%9A%84%E6%97%B6%E5%80%99%EF%BC%8C%E4%B9%9F%E7%BB%8F%E5%B8%B8%E5%87%BA%E7%8E%B0%E5%9B%BE%E7%89%87%E4%B8%8D%E6%98%BE%E7%A4%BA%E7%9A%84%E6%83%85%E5%86%B5%EF%BC%9B) for this.

I will need some code example or a repo where you reproduce this if I should be able to help you.
