### ISSUE TITLE
ng-lazyload-image basic setup not working

### ISSUE THREAD

**Issue by RyaiStudio** [tjoskar/ng-lazyload-image#467]
basic installation setup is not working
`npm install ng-lazyload-image`

**app.module.ts**
```
import { LazyLoadImageModule } from 'ng-lazyload-image';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    SharedModule,
    AppRoutingModule,
    NgxsModule.forRoot(Store, {
      developmentMode: !environment.production,
    }),
    NgxsLoggerPluginModule.forRoot(),
    NgxsDispatchPluginModule.forRoot(),
    NgxsResetPluginModule.forRoot(),
    HttpClientModule,
    LazyLoadImageModule,
  ],
  providers: [],
  exports: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```
this component is lazyloaded on angular route
dinamic component **grid-component.html**
```
<div class="playlist-collection">
  <div
    class="playlist-item"
    *ngFor="let artist of artists"
    (click)="previewArtist(artist)"
  >
    <figure class="image">
      <img
        defaultImage="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM8c+buHgAIFAMzA8bS0AAAAABJRU5ErkJggg=="
        [lazyLoad]="artist.images[0].url"
        alt=""
      />
    </figure>
    <div class="playlist-item--content">
      <h3>{{ artist.name }}</h3>
      <label class="followers">
        <strong>followers : </strong>
        <span>{{ withComma(artist.followers.total) }}</span>
      </label>
      <label class="popularity">
        <strong>popularity : </strong> <span>{{ artist.popularity }}%</span>
      </label>
      <div class="floater">
        <fa-icon [icon]="faEye"></fa-icon>
      </div>
    </div>
  </div>
</div>

```

<img width="866" alt="Screen Shot 2020-06-17 at 4 25 06 PM" src="https://user-images.githubusercontent.com/16729019/84874407-1f5e5100-b0b7-11ea-9ccc-23b93b80028b.png">

- no error on the browser
- no error on the terminal
- no css class triggered

**Comment by tjoskar** [comment]
Is it possible for you to share a small repo? 
I can not reproduce this.

**Comment by tjoskar** [comment]
I just tried to create a simple repo here: https://github.com/tjoskar/ng-lazyload-image-bugs/tree/master/467-basic-setup
(here is the change I made: https://github.com/tjoskar/ng-lazyload-image-bugs/commit/3ee2ee7be1e6f10e83b1c0a93b9902c0310adba4)

**Comment by tjoskar** [comment]
In the print screen you provided is `kitten-small.jpg` set as the default image but in the code have you put `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mM8c+buHgAIFAMzA8bS0AAAAABJRU5ErkJggg==`. Do you use the same code as you send me?

**Comment by RyaiStudio** [comment]
here the link https://github.com/RyaiStudio/lazyload-image-angular

sorry for late reply i'm trying to figure out my self

**Comment by tjoskar** [comment]
Sorry for the late reply but I created a PR for your repo now. I think the main issue was:
```diff
- loadChildren: () => MainModule,
+ loadChildren: () => import('./pages/main/main.module').then(r => r.MainModule),
```

If you want to lazyload the module.

**Comment by RyaiStudio** [comment]
Thanks that's a great help

**Comment by tjoskar** [comment]
I will close this now, but let me know if I can help in any other way
