### ISSUE TITLE
data image binding dynamicaly

### ISSUE THREAD

**Issue by sureshrucko** [tjoskar/ng-lazyload-image#470]
I want to access my base url based on production & staging level 

```html
<img
  class="img-responsive"
  [defaultImage]="'../../../../assets/Reload-1s-200px.gif'"
  [lazyLoad]="'{{imageUrl}}/angular_assets/desktop/images/demo.png'"
  alt=""
>
```

i am not able to access my "imageurl" value because of variable declaye inside of double quotes inside single quotes
please help me some one !

**Comment by tjoskar** [comment]
Does this work for you?
```
[lazyLoad]="imageUrl + '/angular_assets/desktop/images/demo.png'"
```
