### ISSUE TITLE
Image loaded twice only on router link

### ISSUE THREAD

**Issue by asijoumi** [tjoskar/ng-lazyload-image#478]
Hello, 

I read the issues about images loaded twice. But in my case, images are loaded twice only when I use the routerLink.

For exemple, when I go to this page : `mywebsite/documents`, there are some thumbnails and there are loaded once.
But when I go to `mywebsite/documents?page=1` by a link (I mean routerLink and not changing url directly), the thumbnail are loaded twice.

I don't know why exactly this happens like that.

Thanks 😄

**Comment by tjoskar** [comment]
Hi,
I guess you are using devtools in your browser to see that the images are loaded twice? Do you have "Disable Chache" checked? If so, can you try to uncheck it and see if you get the same result.

**Comment by tjoskar** [comment]
If the images are still loaded twice, can you see if the server responds with different headers?

**Comment by asijoumi** [comment]
Hello ! Thanks for answer.

I'm not using the devtools because this happens even in a phone.

When I see the network activity, I see 2 calls for fetching images

**Comment by asijoumi** [comment]
Hi !

Thanks for answer !

I disabled the cache on my computer, but why this effect happens to phone ?

**Comment by tjoskar** [comment]
> I disabled the cache on my computer, but why this effect happens to phone ?

How do you know it is happens on your phone? Do you have connected a devtool or do you look at requests on the server side?
