### ISSUE TITLE
ERROR in node_modules/ng-lazyload-image/src/scroll-hooks/hooks.d.ts(5,48): error TS2304: Cannot find name 'globalThis'.

### ISSUE THREAD

**Issue by Huansheng1** [tjoskar/ng-lazyload-image#481]
错误信息：`ERROR in node_modules/ng-lazyload-image/src/scroll-hooks/hooks.d.ts(5,48): error TS2304: Cannot find name 'globalThis'.`

**Comment by tjoskar** [comment]
It looks like you are using an old version of typescript.
What version of Angular and typescript are you using?

**Comment by Huansheng1** [comment]
> It looks like you are using an old version of typescript.
> What version of Angular and typescript are you using?

`"@angular/core": "~7.1.0",`
```json
"@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
```

**Comment by tjoskar** [comment]
Angular 7 is not supported and soon will Angular drop support for version 8. https://angular.io/guide/releases#support-policy-and-schedule

I would recommend you to upgrade to version 10.

**Comment by Huansheng1** [comment]
> Angular 7 is not supported and soon will Angular drop support for version 8. https://angular.io/guide/releases#support-policy-and-schedule
> 
> I would recommend you to upgrade to version 10.

ok,thanks!
