### ISSUE TITLE
IntersectionObserverHooks has wrong definition of skipLazyLoading method

### ISSUE THREAD

**Issue by Burakovivan** [tjoskar/ng-lazyload-image#483]
Docs says [this](https://www.npmjs.com/package/ng-lazyload-image#hooks)

Exact part im interested in is skipLazyLoading func, docs says it has one argument type of Attributes, and this does not relevant into real code (version 9.0.1 which are latest at the moment)

Class IntersectionObserverHooks has func skipLazyLoading which does not accept any arg, BUT it abstract parent do. Inheritance broken at some point, look this

IntersectionObserverHooks - skipLazyLoading(): boolean;
inherits
abstract SharedHooks - skipLazyLoading(): boolean;
inherits
abstract Hooks - abstracts skipLazyLoading(attributes: Attributes): boolean;

Problem at SharedHooks class. I believed i will fix that with argmunets[0], but it does not helps as code where this func called even does not put 'attributes' argument into func

**Comment by tjoskar** [comment]
Hi @Burakovivan, sorry for the delay. I have not seen this issue until now. I agree it is a issue and it looks like @kp42 has a solution.
