### ISSUE TITLE
Error: getInternalNameofClass() callee on a non-ES5 class: expected LazyLoadImageDirective to have an inner class declaration

### ISSUE THREAD

**Issue by tahera49** [tjoskar/ng-lazyload-image#484]
I’ve tried installing the latest version of ng-lazyload-image and when I try npm start, gives me this error.

Error: getInternalNameofClass() callee on a non-ES5 class: expected LazyLoadImageDirective to have an inner class declaration
NGCC failed.

I need Ivy so can’t disable it. Is there any alternate solution? I’m using Angular 9

**Comment by tjoskar** [comment]
I can not reproduce this. Can you try to upgrade to `ng-lazyload-image@9.1.0`?

**Comment by candy1024** [comment]
@tahera49 same error , i got  ng-lazyload-image@8.0.1 , it worked

**Comment by tjoskar** [comment]
Let me know if this is still an issue and if someone can create a small demo app where we can reproduce this.
