### ISSUE TITLE
please consider exporting `LazyLoadImageDirective` again

### ISSUE THREAD

**Issue by kevinphelps** [tjoskar/ng-lazyload-image#486]
Previous versions exported `LazyLoadImageDirective`. I believe this was changed in version 8. Some use cases require access to the directive class. For example, my application changes image urls in production to use a CDN and that requires access to the directive class for lazy loaded image.

**Comment by tjoskar** [comment]
Sure, sounds reasonable

**Comment by kevinphelps** [comment]
Thanks!
