### ISSUE TITLE
Don't add the loading class when there is not imagePath

### ISSUE THREAD

**Issue by Jonnyprof** [tjoskar/ng-lazyload-image#487]
Hi,
When we receive an image source as null from backend, the class ng-lazyloading is added and never ends with ng-lazyloaded.
I think this is an error because the image will not be loaded:
https://github.com/tjoskar/ng-lazyload-image/blob/09d12121ec177082cd4e7fd65541920f3206925f/src/lazyload-image.directive.ts#L71-L73

We have a css transition (starting from opacity: 0) from ng-lazyloading to ng-lazyloaded and it doesn't work.
It's possible to workaround this with a hook:
```ts
  setup(attr: Attributes): void {
    super.setup(attr);

    if (!attr.imagePath) {
      attr.element.classList.remove('ng-lazyloading');
    }
  }
```
but IMHO the class is not correct.
I can do the PR if you need it.

Thanks

**Comment by tjoskar** [comment]
Hi @Jonnyprof,
What do you think of skip calling setup if the image path is empty?

Something like:
```diff
-  tap((attributes) => this.hooks.onAttributeChange(attributes)),
-  tap((attributes) => attributes.onStateChange.emit({ reason: 'setup' })),
-  tap((attributes) => this.hooks.setup(attributes)),
-  switchMap((attributes) => {
-    if (!attributes.imagePath) {
-      return never();
-    }
-    return this.hooks.getObservable(attributes).pipe(lazyLoadImage(this.hooks, attributes));
-  })
+  switchMap((attributes) => {
+    this.hooks.onAttributeChange(attributes);
+    if (!attributes.imagePath) {
+      return never();
+    }
+    attributes.onStateChange.emit({ reason: 'setup' });
+    this.hooks.setup(attributes);
+    return this.hooks.getObservable(attributes).pipe(lazyLoadImage(this.hooks, attributes));
+  })
```

**Comment by Jonnyprof** [comment]
Hi @tjoskar,
I think it's important to execute https://github.com/tjoskar/ng-lazyload-image/blob/09d12121ec177082cd4e7fd65541920f3206925f/src/shared-hooks/hooks.ts#L9 In our case, we add a custom class in the setup but it can be used for other purposes because is a hook.
For me, the resolution of this issue is as easy as an if:
```typescript
    setImageAndSourcesToDefault(attributes.element, attributes.defaultImagePath, attributes.useSrcset);
    if (attributes.imagePath) {
        addCssClassName(attributes.element, cssClassNames.loading);
    }

    if (hasCssClassName(attributes.element, cssClassNames.loaded)) {
      removeCssClassName(attributes.element, cssClassNames.loaded);
    }
  }
```

What do you think?

**Comment by tjoskar** [comment]
You are right,  we should set the default image. I would accept the change above. Do you want to create a PR?

**Comment by Jonnyprof** [comment]
Done!
