### ISSUE TITLE
carousel Images are not loaded even if it is in viewport

### ISSUE THREAD

**Issue by sathishkumarsubramani** [tjoskar/ng-lazyload-image#492]
Hi Team,

We have used the lazyload in our application and also we used owl carousel for the slider purpose.

Initially images that are in view port only loaded when scrolling. We have more than 20 slides, next slide images are not showing.

If we scroll little bit up or down then those images are loading.

Can you guys please help out to fix this issue.

Also is it possible to trigger the images by click event?

Thanks in advance.

**Comment by tjoskar** [comment]
Hi,
Are you using the [IntersectionObserver](https://github.com/tjoskar/ng-lazyload-image#intersectionobserver) or [Scroll listener](https://github.com/tjoskar/ng-lazyload-image#scroll-listener)?

**Comment by sathishkumarsubramani** [comment]
We are not using above methods, we used scrollpreset for lazy loading.

**Comment by sathishkumarsubramani** [comment]
Fixed the issue by updating to later version.

Thanks.

**Comment by marcomiguel** [comment]
Hi!
I have the same issue :(
I'm use v9.1.0
@sathishkumarsubramani could you tell me which version you are using, please?
 
![image](https://user-images.githubusercontent.com/1157124/115803585-cf22e000-a3a6-11eb-9ab2-ed2f6ec35c59.png)

**Comment by sathishkumarsubramani** [comment]
> Hi!
> I have the same issue :(
> I'm use v9.1.0
> @sathishkumarsubramani could you tell me which version you are using, please?
>  
> ![image](https://user-images.githubusercontent.com/1157124/115803585-cf22e000-a3a6-11eb-9ab2-ed2f6ec35c59.png)
> 

Angular : 8
Lazy load: 9.1
Owl carousel : 5
