### ISSUE TITLE
Hooks not working in Angular 12

### ISSUE THREAD

**Issue by calliostro** [tjoskar/ng-lazyload-image#515]
Hello Oskar,

great module, exactly what I was looking for.

Creating hooks doesn't seem to be supported in Angular 12. I tried some of your examples in documentation and log an output inside `loadImage()` method on console. Method is executed in Angular 11 but not the new version.

Maybe you can check?

Regards
Joey

**Comment by tjoskar** [comment]
Hi @calliostro,

Sorry for my late reply. I can't reproduce the issue. I created a stackblitz here with Angular 12 and it seams to be working fine: https://stackblitz.com/edit/angular-ivy-iaulsh?file=src%2Fapp%2Fapp.module.ts Can you reproduce the issue in a small repo?

**Comment by calliostro** [comment]
Hello @tjoskar ,

Thanks for your reply and your test and the example provided.

I stayed with Angular 11 "back then". I have now updated the project again to Angualar 12 and your component works.

Hard to say why I had the problems back then. Maybe I made a mistake or it was a problem in Angular.

In any case, thanks again and best regards!

Joey
