### ISSUE TITLE
Only default image is loading on Bootstrap modal

### ISSUE THREAD

**Issue by shubhddn01** [tjoskar/ng-lazyload-image#531]
This package is not working when I am rendering the image on Bootstrap Modal. The only default image is loaded and out of 10 times, once or twice  the actual image is rendering which also takes a lot of time. 

**Below are the following details :**

- Node Env : v10.10.0
- Angular CLI : 7.3.10
- OS : linux x64
- Angular : 7.2.16
- Bootstrap : 4.6.0
- ng-lazyload-image : 5.1.2

**Sample Code is same as in documentation:** 

`import { Component } from '@angular/core';
 
@Component({
  selector: 'image',
  template: ` <img [defaultImage]="defaultImage" [lazyLoad]="image" /> `,
})
class ImageComponent {
  defaultImage = 'https://www.placecage.com/1000/1000';
  image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
}`

This code is working fine, when I am not using the bootstrap modal.

**Thanks in advance!**

**Comment by tjoskar** [comment]
Hi,
Are you using the default, IntersectionObserver, or the Scroll listener? Aka. how do you setup `ng-lazyload-image` in your `NgModule`?

**Comment by shubhddn01** [comment]
I don't what wrong I was doing, suddenly after posting the issue, it's working fine for me.
Thanks for your response man.
