### ISSUE TITLE
Angular 13 ivy. Processing legacy "View Engine" libraries

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [tjoskar/ng-lazyload-image#537]
ng serve

Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:

`ng-lazyload-image [es2015/esm2015] (git+https://github.com/tjoskar/ng-lazyload-image.git)`

Encourage the library authors to publish an Ivy distribution.

Please, update package

**Comment by tjoskar** [comment]
@beyondtheobservableuniverse Hi, can you try version `9.1.1`?

**Comment by beyondtheobservableuniverse** [comment]
Hi

Thank you! Works for me.
